//! Deterministic synthetic fixture data generator for know-now.
//!
//! Produces CSV files with obviously-synthetic rows that respect
//! logical types, semantic types, required fields, and FK relationships.
//! Uses a seeded PRNG — no system clock, no entropy source.

use std::collections::BTreeMap;

use know_now_codegen::artifact::{ArtifactDescriptor, ArtifactKind};
use know_now_codegen::generator::{GenerationError, Generator};
use know_now_contract::contract::{
    ContractAttribute, ContractEntity, ContractRelationship, GeneratorContract,
};

mod prng;
mod values;

use prng::SeededRng;

const GENERATOR_NAME: &str = "know_now_gen_fixtures";
const DEFAULT_ROW_COUNT: usize = 10;
const DEFAULT_SEED: u64 = 0x6b6e_6f77_6e6f_7721;

pub struct FixtureGenerator {
    version: String,
    seed: u64,
    row_count: usize,
}

impl FixtureGenerator {
    #[must_use]
    pub fn new() -> Self {
        Self {
            version: env!("CARGO_PKG_VERSION").to_owned(),
            seed: DEFAULT_SEED,
            row_count: DEFAULT_ROW_COUNT,
        }
    }

    #[must_use]
    pub fn with_seed(mut self, seed: u64) -> Self {
        self.seed = seed;
        self
    }

    #[must_use]
    pub fn with_row_count(mut self, count: usize) -> Self {
        self.row_count = count;
        self
    }
}

impl Default for FixtureGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for FixtureGenerator {
    fn name(&self) -> &str {
        GENERATOR_NAME
    }

    fn version(&self) -> &str {
        &self.version
    }

    #[allow(clippy::too_many_lines)]
    fn generate(
        &self,
        contract: &GeneratorContract,
    ) -> Result<Vec<ArtifactDescriptor>, Vec<GenerationError>> {
        if contract.entities.is_empty() {
            return Ok(vec![]);
        }

        let mut rng = SeededRng::new(self.seed);
        let mut artifacts = Vec::new();

        let generation_order = topological_sort(&contract.entities, &contract.relationships);
        let mut pk_pools: BTreeMap<String, Vec<String>> = BTreeMap::new();

        for entity_name in &generation_order {
            let entity = contract
                .entities
                .iter()
                .find(|e| &e.name == entity_name)
                .unwrap();

            let csv = generate_entity_csv(
                entity,
                &contract.relationships,
                &pk_pools,
                &mut rng,
                self.row_count,
            );

            let pk_values: Vec<String> = extract_pk_values(entity, &csv);
            pk_pools.insert(entity.name.clone(), pk_values);

            artifacts.push(ArtifactDescriptor {
                path: format!("fixtures/{}.csv", entity.name),
                kind: ArtifactKind::MarkdownDoc,
                artifact_id: format!("art_fixture_{}", entity.name),
                generator: GENERATOR_NAME.into(),
                generator_version: self.version.clone(),
                content: csv,
                metadata_object_ids: vec![entity.id.clone()],
            });
        }

        let readme = generate_readme(&generation_order, self.seed, self.row_count, &self.version);
        artifacts.push(ArtifactDescriptor {
            path: "fixtures/README.md".into(),
            kind: ArtifactKind::MarkdownDoc,
            artifact_id: "art_fixture_readme".into(),
            generator: GENERATOR_NAME.into(),
            generator_version: self.version.clone(),
            content: readme,
            metadata_object_ids: vec![],
        });

        artifacts.sort_by(|a, b| a.path.cmp(&b.path));
        Ok(artifacts)
    }
}

fn generate_entity_csv(
    entity: &ContractEntity,
    relationships: &[ContractRelationship],
    pk_pools: &BTreeMap<String, Vec<String>>,
    rng: &mut SeededRng,
    row_count: usize,
) -> String {
    let mut lines = Vec::new();

    lines.push(format!(
        "# SYNTHETIC DATA — do not use in production. Generated by {GENERATOR_NAME}."
    ));

    let header: Vec<&str> = entity.attributes.iter().map(|a| a.name.as_str()).collect();
    lines.push(header.join(","));

    for row_idx in 0..row_count {
        let row: Vec<String> = entity
            .attributes
            .iter()
            .map(|attr| {
                generate_cell(attr, entity, relationships, pk_pools, rng, row_idx)
            })
            .collect();
        lines.push(row.join(","));
    }

    lines.push(String::new());
    lines.join("\n")
}

fn generate_cell(
    attr: &ContractAttribute,
    entity: &ContractEntity,
    relationships: &[ContractRelationship],
    pk_pools: &BTreeMap<String, Vec<String>>,
    rng: &mut SeededRng,
    row_idx: usize,
) -> String {
    let is_required = attr.required.unwrap_or(false);
    if !is_required && rng.next_u64().is_multiple_of(10) {
        return String::new();
    }

    if let Some(fk_pool) = find_fk_pool(attr, entity, relationships, pk_pools) {
        if !fk_pool.is_empty() {
            let idx = rng.next_u64() as usize % fk_pool.len();
            return fk_pool[idx].clone();
        }
    }

    if entity.business_key.contains(&attr.name) || is_pk_like(attr) {
        return values::generate_pk(attr, rng, row_idx);
    }

    if let Some(ref semantic) = attr.semantic_type {
        return values::generate_semantic(semantic, rng, row_idx);
    }

    let logical = attr.logical_type.as_deref().unwrap_or("string");
    values::generate_logical(logical, rng, row_idx)
}

fn find_fk_pool<'a>(
    attr: &ContractAttribute,
    entity: &ContractEntity,
    relationships: &[ContractRelationship],
    pk_pools: &'a BTreeMap<String, Vec<String>>,
) -> Option<&'a Vec<String>> {
    for rel in relationships {
        if rel.from_entity == entity.name && rel.from_key.as_deref() == Some(&attr.name) {
            return pk_pools.get(&rel.to_entity);
        }
    }
    None
}

fn is_pk_like(attr: &ContractAttribute) -> bool {
    attr.is_unique == Some(true) && attr.required == Some(true)
}

fn extract_pk_values(entity: &ContractEntity, csv: &str) -> Vec<String> {
    let pk_attr = entity.business_key.first().or_else(|| {
        entity
            .attributes
            .iter()
            .find(|a| is_pk_like(a))
            .map(|a| &a.name)
    });

    let Some(pk_name) = pk_attr else {
        return vec![];
    };

    let mut lines = csv.lines().filter(|l| !l.starts_with('#'));
    let Some(header_line) = lines.next() else {
        return vec![];
    };

    let headers: Vec<&str> = header_line.split(',').collect();
    let Some(pk_idx) = headers.iter().position(|h| h == pk_name) else {
        return vec![];
    };

    lines
        .filter(|l| !l.is_empty())
        .filter_map(|line| {
            let fields: Vec<&str> = line.split(',').collect();
            fields.get(pk_idx).map(|v| (*v).to_owned())
        })
        .collect()
}

fn topological_sort(
    entities: &[ContractEntity],
    relationships: &[ContractRelationship],
) -> Vec<String> {
    let entity_names: Vec<String> = entities.iter().map(|e| e.name.clone()).collect();
    let mut deps: BTreeMap<String, Vec<String>> = BTreeMap::new();
    for name in &entity_names {
        deps.insert(name.clone(), vec![]);
    }

    for rel in relationships {
        if rel.from_entity != rel.to_entity {
            if let Some(dep_list) = deps.get_mut(&rel.from_entity) {
                if entity_names.contains(&rel.to_entity) {
                    dep_list.push(rel.to_entity.clone());
                }
            }
        }
    }

    let visited: BTreeMap<String, bool> = BTreeMap::new();
    let mut result = Vec::new();

    for name in &entity_names {
        topo_visit(name, &deps, &visited, &mut result);
    }

    result
}

fn topo_visit(
    name: &str,
    deps: &BTreeMap<String, Vec<String>>,
    visited: &BTreeMap<String, bool>,
    result: &mut Vec<String>,
) {
    if visited.contains_key(name) {
        return;
    }
    let mut visited = visited.clone();
    visited.insert(name.to_owned(), true);

    if let Some(dep_list) = deps.get(name) {
        for dep in dep_list {
            topo_visit(dep, deps, &visited, result);
        }
    }

    if !result.contains(&name.to_owned()) {
        result.push(name.to_owned());
    }
}

fn generate_readme(
    entities: &[String],
    seed: u64,
    row_count: usize,
    version: &str,
) -> String {
    let mut lines = Vec::new();
    lines.push(format!(
        "<!-- Generated by know-now. Generator: {GENERATOR_NAME}. Version: {version}. Do not edit directly unless you intend to fork this artifact. -->"
    ));
    lines.push(String::new());
    lines.push("# Synthetic Fixture Data".to_owned());
    lines.push(String::new());
    lines.push(
        "**This data is synthetic and must not be used in production.**".to_owned(),
    );
    lines.push(String::new());
    lines.push(format!("- Seed: `{seed:#018x}`"));
    lines.push(format!("- Rows per entity: {row_count}"));
    lines.push(format!("- Generator: `{GENERATOR_NAME}` v{version}"));
    lines.push(String::new());
    lines.push("## Files".to_owned());
    lines.push(String::new());
    for entity in entities {
        lines.push(format!("- `{entity}.csv`"));
    }
    lines.push(String::new());

    lines.join("\n")
}

#[cfg(test)]
mod tests {
    use super::*;
    use know_now_contract::contract::{
        ContractAttribute, ContractEntity, ContractProject, ContractRelationship, ContractTrace,
        GeneratorContract,
    };

    fn customer_entity() -> ContractEntity {
        ContractEntity {
            id: "ent_customer".into(),
            name: "customer".into(),
            display_name: None,
            domain: None,
            module: None,
            owner: None,
            steward: None,
            classification: None,
            retention_policy: None,
            description: None,
            entity_type: None,
            tags: vec![],
            business_key: vec!["id".into()],
            attributes: vec![
                ContractAttribute {
                    id: "attr_id".into(),
                    name: "id".into(),
                    logical_type: Some("integer".into()),
                    semantic_type: None,
                    sensitivity: None,
                    pii: None,
                    required: Some(true),
                    is_unique: Some(true),
                    constraints: vec![],
                    description: None,
                    attr_type: None,
                },
                ContractAttribute {
                    id: "attr_email".into(),
                    name: "email".into(),
                    logical_type: Some("string".into()),
                    semantic_type: Some("email".into()),
                    sensitivity: None,
                    pii: Some(true),
                    required: Some(true),
                    is_unique: None,
                    constraints: vec![],
                    description: None,
                    attr_type: None,
                },
                ContractAttribute {
                    id: "attr_active".into(),
                    name: "active".into(),
                    logical_type: Some("boolean".into()),
                    semantic_type: None,
                    sensitivity: None,
                    pii: None,
                    required: Some(true),
                    is_unique: None,
                    constraints: vec![],
                    description: None,
                    attr_type: None,
                },
                ContractAttribute {
                    id: "attr_notes".into(),
                    name: "notes".into(),
                    logical_type: Some("string".into()),
                    semantic_type: None,
                    sensitivity: None,
                    pii: None,
                    required: None,
                    is_unique: None,
                    constraints: vec![],
                    description: None,
                    attr_type: None,
                },
            ],
        }
    }

    fn order_entity() -> ContractEntity {
        ContractEntity {
            id: "ent_order".into(),
            name: "order".into(),
            display_name: None,
            domain: None,
            module: None,
            owner: None,
            steward: None,
            classification: None,
            retention_policy: None,
            description: None,
            entity_type: None,
            tags: vec![],
            business_key: vec!["id".into()],
            attributes: vec![
                ContractAttribute {
                    id: "attr_order_id".into(),
                    name: "id".into(),
                    logical_type: Some("integer".into()),
                    semantic_type: None,
                    sensitivity: None,
                    pii: None,
                    required: Some(true),
                    is_unique: Some(true),
                    constraints: vec![],
                    description: None,
                    attr_type: None,
                },
                ContractAttribute {
                    id: "attr_order_customer_id".into(),
                    name: "customer_id".into(),
                    logical_type: Some("integer".into()),
                    semantic_type: None,
                    sensitivity: None,
                    pii: None,
                    required: Some(true),
                    is_unique: None,
                    constraints: vec![],
                    description: None,
                    attr_type: None,
                },
                ContractAttribute {
                    id: "attr_order_total".into(),
                    name: "total".into(),
                    logical_type: Some("decimal".into()),
                    semantic_type: None,
                    sensitivity: None,
                    pii: None,
                    required: Some(true),
                    is_unique: None,
                    constraints: vec![],
                    description: None,
                    attr_type: None,
                },
            ],
        }
    }

    fn minimal_contract() -> GeneratorContract {
        GeneratorContract {
            contract_version: "1.0".into(),
            project: Some(ContractProject {
                name: "demo".into(),
                description: None,
                owner: None,
                tags: vec![],
            }),
            target_database: None,
            entities: vec![customer_entity()],
            relationships: vec![],
            source_systems: vec![],
            quality_rules: vec![],
            governance: None,
            open_questions: vec![],
            assumptions: vec![],
            trace: ContractTrace::default(),
        }
    }

    fn contract_with_fk() -> GeneratorContract {
        GeneratorContract {
            contract_version: "1.0".into(),
            project: None,
            target_database: None,
            entities: vec![customer_entity(), order_entity()],
            relationships: vec![ContractRelationship {
                id: "rel_order_customer".into(),
                from_entity: "order".into(),
                to_entity: "customer".into(),
                cardinality: Some("many_to_one".into()),
                from_key: Some("customer_id".into()),
                to_key: Some("id".into()),
                description: None,
            }],
            source_systems: vec![],
            quality_rules: vec![],
            governance: None,
            open_questions: vec![],
            assumptions: vec![],
            trace: ContractTrace::default(),
        }
    }

    #[test]
    fn empty_contract_produces_no_artifacts() {
        let gen = FixtureGenerator::new();
        let contract = GeneratorContract {
            contract_version: "1.0".into(),
            project: None,
            target_database: None,
            entities: vec![],
            relationships: vec![],
            source_systems: vec![],
            quality_rules: vec![],
            governance: None,
            open_questions: vec![],
            assumptions: vec![],
            trace: ContractTrace::default(),
        };
        assert!(gen.generate(&contract).unwrap().is_empty());
    }

    #[test]
    fn produces_csv_and_readme() {
        let gen = FixtureGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        assert!(artifacts.iter().any(|a| a.path == "fixtures/customer.csv"));
        assert!(artifacts.iter().any(|a| a.path == "fixtures/README.md"));
    }

    #[test]
    fn csv_has_synthetic_header_comment() {
        let gen = FixtureGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let csv = &artifacts
            .iter()
            .find(|a| a.path.ends_with(".csv"))
            .unwrap()
            .content;
        assert!(csv.starts_with("# SYNTHETIC DATA"));
    }

    #[test]
    fn csv_has_correct_column_headers() {
        let gen = FixtureGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let csv = &artifacts
            .iter()
            .find(|a| a.path.ends_with(".csv"))
            .unwrap()
            .content;
        let header_line = csv.lines().find(|l| !l.starts_with('#')).unwrap();
        assert_eq!(header_line, "id,email,active,notes");
    }

    #[test]
    fn csv_has_correct_row_count() {
        let gen = FixtureGenerator::new().with_row_count(5);
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let csv = &artifacts
            .iter()
            .find(|a| a.path.ends_with(".csv"))
            .unwrap()
            .content;
        let data_rows = csv
            .lines()
            .filter(|l| !l.starts_with('#') && !l.is_empty())
            .count()
            - 1; // subtract header
        assert_eq!(data_rows, 5);
    }

    #[test]
    fn deterministic_output() {
        let gen = FixtureGenerator::new().with_seed(42);
        let contract = minimal_contract();
        let a = gen.generate(&contract).unwrap();

        let gen2 = FixtureGenerator::new().with_seed(42);
        let b = gen2.generate(&contract).unwrap();

        for (x, y) in a.iter().zip(b.iter()) {
            assert_eq!(x.content, y.content, "artifact {} differs", x.path);
        }
    }

    #[test]
    fn different_seed_produces_different_output() {
        let contract = minimal_contract();
        let a = FixtureGenerator::new()
            .with_seed(1)
            .generate(&contract)
            .unwrap();
        let b = FixtureGenerator::new()
            .with_seed(2)
            .generate(&contract)
            .unwrap();
        let csv_a = &a.iter().find(|a| a.path.ends_with(".csv")).unwrap().content;
        let csv_b = &b.iter().find(|a| a.path.ends_with(".csv")).unwrap().content;
        assert_ne!(csv_a, csv_b);
    }

    #[test]
    fn fk_values_reference_parent_pk() {
        let gen = FixtureGenerator::new().with_row_count(5);
        let artifacts = gen.generate(&contract_with_fk()).unwrap();

        let customer_csv = &artifacts
            .iter()
            .find(|a| a.path == "fixtures/customer.csv")
            .unwrap()
            .content;
        let customer_ids: Vec<String> = customer_csv
            .lines()
            .filter(|l| !l.starts_with('#') && !l.is_empty())
            .skip(1) // header
            .filter_map(|line| line.split(',').next().map(String::from))
            .collect();

        let order_csv = &artifacts
            .iter()
            .find(|a| a.path == "fixtures/order.csv")
            .unwrap()
            .content;
        let order_customer_ids: Vec<String> = order_csv
            .lines()
            .filter(|l| !l.starts_with('#') && !l.is_empty())
            .skip(1)
            .filter_map(|line| line.split(',').nth(1).map(String::from))
            .collect();

        for fk_val in &order_customer_ids {
            assert!(
                customer_ids.contains(fk_val),
                "FK value '{fk_val}' not found in parent PK pool {customer_ids:?}"
            );
        }
    }

    #[test]
    fn parent_entity_generated_before_child() {
        let order = topological_sort(
            &[customer_entity(), order_entity()],
            &[ContractRelationship {
                id: "rel".into(),
                from_entity: "order".into(),
                to_entity: "customer".into(),
                cardinality: None,
                from_key: Some("customer_id".into()),
                to_key: Some("id".into()),
                description: None,
            }],
        );
        let cust_idx = order.iter().position(|n| n == "customer").unwrap();
        let ord_idx = order.iter().position(|n| n == "order").unwrap();
        assert!(cust_idx < ord_idx);
    }

    #[test]
    fn no_crlf_in_output() {
        let gen = FixtureGenerator::new();
        let artifacts = gen.generate(&contract_with_fk()).unwrap();
        for artifact in &artifacts {
            assert!(
                !artifact.content.contains('\r'),
                "NFR-PO3: LF only in {}",
                artifact.path
            );
        }
    }

    #[test]
    fn required_fields_never_empty() {
        let gen = FixtureGenerator::new().with_row_count(50);
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let csv = &artifacts
            .iter()
            .find(|a| a.path.ends_with(".csv"))
            .unwrap()
            .content;
        for line in csv.lines().filter(|l| !l.starts_with('#') && !l.is_empty()).skip(1) {
            let fields: Vec<&str> = line.split(',').collect();
            assert!(!fields[0].is_empty(), "id (required) must not be empty");
            assert!(!fields[1].is_empty(), "email (required) must not be empty");
            assert!(!fields[2].is_empty(), "active (required) must not be empty");
        }
    }

    #[test]
    fn pk_values_are_unique() {
        let gen = FixtureGenerator::new().with_row_count(50);
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let csv = &artifacts
            .iter()
            .find(|a| a.path.ends_with(".csv"))
            .unwrap()
            .content;
        let ids: Vec<&str> = csv
            .lines()
            .filter(|l| !l.starts_with('#') && !l.is_empty())
            .skip(1)
            .filter_map(|line| line.split(',').next())
            .collect();
        let mut deduped = ids.clone();
        deduped.sort();
        deduped.dedup();
        assert_eq!(ids.len(), deduped.len(), "PK values must be unique");
    }

    #[test]
    fn readme_contains_seed() {
        let gen = FixtureGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let readme = &artifacts
            .iter()
            .find(|a| a.path.ends_with("README.md"))
            .unwrap()
            .content;
        assert!(readme.contains("Synthetic"));
        assert!(readme.contains(&format!("{DEFAULT_SEED:#018x}")));
    }

    #[test]
    fn generator_is_send_sync() {
        fn assert_send_sync<T: Send + Sync>() {}
        assert_send_sync::<FixtureGenerator>();
    }

    #[test]
    fn artifacts_sorted_by_path() {
        let gen = FixtureGenerator::new();
        let artifacts = gen.generate(&contract_with_fk()).unwrap();
        let paths: Vec<&str> = artifacts.iter().map(|a| a.path.as_str()).collect();
        let mut sorted = paths.clone();
        sorted.sort();
        assert_eq!(paths, sorted);
    }
}
