use crate::ddl::{CreateTableStatement, OwnershipHeader};
use crate::identifier::Identifier;

#[derive(Debug, Clone)]
pub struct LineTrace {
    pub line_start: u32,
    pub line_end: u32,
    pub metadata_object_ids: Vec<String>,
}

#[derive(Debug, Clone)]
pub struct EmittedDdl {
    pub sql: String,
    pub traces: Vec<LineTrace>,
}

pub fn emit_document(
    statements: &mut [CreateTableStatement],
    header: &OwnershipHeader,
) -> EmittedDdl {
    statements.sort_by(|a, b| a.name.as_str().cmp(b.name.as_str()));

    let mut lines: Vec<String> = Vec::new();
    let mut traces: Vec<LineTrace> = Vec::new();

    emit_header(header, &mut lines);

    for (i, stmt) in statements.iter().enumerate() {
        if i > 0 || !lines.is_empty() {
            lines.push(String::new());
        }
        emit_create_table(stmt, &mut lines, &mut traces);
    }

    lines.push(String::new());

    EmittedDdl {
        sql: lines.join("\n"),
        traces,
    }
}

fn emit_header(header: &OwnershipHeader, lines: &mut Vec<String>) {
    lines.push("-- Generated by know-now.".to_owned());
    lines.push(format!("-- Artifact ID: {}", header.artifact_id));
    lines.push(format!("-- Generator: {}", header.generator));
    lines.push(format!(
        "-- Generator version: {}",
        header.generator_version
    ));
    lines.push(format!("-- Input hash: {}", header.input_hash));
    lines.push("-- Manifest path: generated/manifest.json".to_owned());
    lines.push("-- Do not edit directly unless you intend to fork this artifact.".to_owned());
}

fn emit_create_table(
    stmt: &CreateTableStatement,
    lines: &mut Vec<String>,
    traces: &mut Vec<LineTrace>,
) {
    let table_start = lines.len() as u32 + 1;

    lines.push(format!("CREATE TABLE {} (", stmt.qualified_name()));

    let mut parts: Vec<String> = Vec::new();
    let mut column_traces: Vec<(u32, Vec<String>)> = Vec::new();

    for col in &stmt.columns {
        let col_line = (lines.len() + parts.len() + 1) as u32;
        let mut def = format!("    {} {}", col.name.quoted(), col.sql_type.sql_keyword());
        if !col.nullable {
            def.push_str(" NOT NULL");
        }
        parts.push(def);
        column_traces.push((
            col_line,
            vec![stmt.entity_id.clone(), col.metadata_object_id.clone()],
        ));
    }

    if let Some(pk) = &stmt.primary_key {
        let cols: Vec<String> = pk.columns.iter().map(Identifier::quoted).collect();
        parts.push(format!("    PRIMARY KEY ({})", cols.join(", ")));
    }

    for (i, part) in parts.iter().enumerate() {
        if i < parts.len() - 1 {
            lines.push(format!("{part},"));
        } else {
            lines.push(part.clone());
        }
    }

    lines.push(");".to_owned());
    let table_end = lines.len() as u32;

    traces.push(LineTrace {
        line_start: table_start,
        line_end: table_end,
        metadata_object_ids: vec![stmt.entity_id.clone()],
    });

    for (col_line, ids) in column_traces {
        traces.push(LineTrace {
            line_start: col_line,
            line_end: col_line,
            metadata_object_ids: ids,
        });
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::ddl::{ColumnDef, PrimaryKeyConstraint, SqlType};
    use crate::identifier::Identifier;

    fn sample_header() -> OwnershipHeader {
        OwnershipHeader {
            artifact_id: "art_pg_schema".into(),
            generator: "know_now_gen_postgres".into(),
            generator_version: "0.1.0".into(),
            input_hash: "sha256:abc123".into(),
        }
    }

    fn sample_table() -> CreateTableStatement {
        CreateTableStatement {
            schema: None,
            name: Identifier::new("customer").unwrap(),
            columns: vec![
                ColumnDef {
                    name: Identifier::new("id").unwrap(),
                    sql_type: SqlType::Integer,
                    nullable: false,
                    metadata_object_id: "attr_customer_id".into(),
                },
                ColumnDef {
                    name: Identifier::new("email").unwrap(),
                    sql_type: SqlType::Text,
                    nullable: true,
                    metadata_object_id: "attr_customer_email".into(),
                },
            ],
            primary_key: Some(PrimaryKeyConstraint {
                columns: vec![Identifier::new("id").unwrap()],
            }),
            entity_id: "ent_customer".into(),
        }
    }

    #[test]
    fn emits_ownership_header() {
        let mut stmts = vec![sample_table()];
        let result = emit_document(&mut stmts, &sample_header());
        assert!(result.sql.starts_with("-- Generated by know-now.\n"));
        assert!(result.sql.contains("-- Artifact ID: art_pg_schema"));
        assert!(result.sql.contains("-- Generator: know_now_gen_postgres"));
        assert!(result.sql.contains("-- Input hash: sha256:abc123"));
        assert!(result
            .sql
            .contains("-- Manifest path: generated/manifest.json"));
        assert!(result
            .sql
            .contains("-- Do not edit directly unless you intend to fork this artifact."));
    }

    #[test]
    fn emits_create_table() {
        let mut stmts = vec![sample_table()];
        let result = emit_document(&mut stmts, &sample_header());
        assert!(result.sql.contains("CREATE TABLE \"customer\" ("));
        assert!(result.sql.contains("    \"id\" INTEGER NOT NULL,"));
        assert!(result.sql.contains("    \"email\" TEXT,"));
        assert!(result.sql.contains("    PRIMARY KEY (\"id\")"));
        assert!(result.sql.contains(");"));
    }

    #[test]
    fn tables_sorted_alphabetically() {
        let mut stmts = vec![
            CreateTableStatement {
                schema: None,
                name: Identifier::new("zebra").unwrap(),
                columns: vec![],
                primary_key: None,
                entity_id: "ent_zebra".into(),
            },
            CreateTableStatement {
                schema: None,
                name: Identifier::new("alpha").unwrap(),
                columns: vec![],
                primary_key: None,
                entity_id: "ent_alpha".into(),
            },
        ];
        let result = emit_document(&mut stmts, &sample_header());
        let alpha_pos = result.sql.find("\"alpha\"").unwrap();
        let zebra_pos = result.sql.find("\"zebra\"").unwrap();
        assert!(alpha_pos < zebra_pos);
    }

    #[test]
    fn deterministic_across_runs() {
        let header = sample_header();
        let sql1 = emit_document(&mut [sample_table()], &header).sql;
        let sql2 = emit_document(&mut [sample_table()], &header).sql;
        assert_eq!(sql1, sql2);
    }

    #[test]
    fn no_crlf_line_endings() {
        let mut stmts = vec![sample_table()];
        let result = emit_document(&mut stmts, &sample_header());
        assert!(!result.sql.contains('\r'), "must use LF, not CRLF");
    }

    #[test]
    fn traces_cover_table() {
        let mut stmts = vec![sample_table()];
        let result = emit_document(&mut stmts, &sample_header());
        let table_trace = result
            .traces
            .iter()
            .find(|t| t.metadata_object_ids == vec!["ent_customer"])
            .expect("should have entity trace");
        assert!(table_trace.line_start > 0);
        assert!(table_trace.line_end >= table_trace.line_start);
    }

    #[test]
    fn traces_cover_columns() {
        let mut stmts = vec![sample_table()];
        let result = emit_document(&mut stmts, &sample_header());
        let col_traces: Vec<_> = result
            .traces
            .iter()
            .filter(|t| t.metadata_object_ids.len() == 2)
            .collect();
        assert_eq!(col_traces.len(), 2);
        assert!(col_traces[0]
            .metadata_object_ids
            .contains(&"attr_customer_id".to_owned()));
        assert!(col_traces[1]
            .metadata_object_ids
            .contains(&"attr_customer_email".to_owned()));
    }

    #[test]
    fn empty_document() {
        let mut stmts: Vec<CreateTableStatement> = vec![];
        let result = emit_document(&mut stmts, &sample_header());
        assert!(result.sql.contains("-- Generated by know-now."));
        assert!(result.traces.is_empty());
    }

    #[test]
    fn table_without_primary_key() {
        let mut stmts = vec![CreateTableStatement {
            schema: None,
            name: Identifier::new("staging_raw").unwrap(),
            columns: vec![ColumnDef {
                name: Identifier::new("payload").unwrap(),
                sql_type: SqlType::Jsonb,
                nullable: true,
                metadata_object_id: "attr_raw_payload".into(),
            }],
            primary_key: None,
            entity_id: "ent_staging".into(),
        }];
        let result = emit_document(&mut stmts, &sample_header());
        assert!(result.sql.contains("\"payload\" JSONB"));
        assert!(!result.sql.contains("PRIMARY KEY"));
    }

    #[test]
    fn schema_qualified_table() {
        let mut stmts = vec![CreateTableStatement {
            schema: Some(Identifier::new("analytics").unwrap()),
            name: Identifier::new("events").unwrap(),
            columns: vec![],
            primary_key: None,
            entity_id: "ent_events".into(),
        }];
        let result = emit_document(&mut stmts, &sample_header());
        assert!(result.sql.contains("CREATE TABLE \"analytics\".\"events\""));
    }
}
