//! Markdown and Mermaid documentation generator crate for know-now.
//!
//! Responsibility is defined in PRD section 8.2 (workspace layout).

use know_now_codegen::artifact::{ArtifactDescriptor, ArtifactKind};
use know_now_codegen::generator::{GenerationError, Generator};
use know_now_contract::contract::{ContractAttribute, ContractEntity, GeneratorContract};

const GENERATOR_NAME: &str = "know_now_gen_docs";

pub struct DocsGenerator {
    version: String,
}

impl DocsGenerator {
    #[must_use]
    pub fn new() -> Self {
        Self {
            version: env!("CARGO_PKG_VERSION").to_owned(),
        }
    }
}

impl Default for DocsGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for DocsGenerator {
    fn name(&self) -> &str {
        GENERATOR_NAME
    }

    fn version(&self) -> &str {
        &self.version
    }

    fn generate(
        &self,
        contract: &GeneratorContract,
    ) -> Result<Vec<ArtifactDescriptor>, Vec<GenerationError>> {
        let mut artifacts = Vec::new();

        for entity in &contract.entities {
            artifacts.push(generate_entity_page(entity, &self.version));
        }

        artifacts.sort_by(|a, b| a.path.cmp(&b.path));

        Ok(artifacts)
    }
}

fn generate_entity_page(entity: &ContractEntity, generator_version: &str) -> ArtifactDescriptor {
    let mut lines: Vec<String> = Vec::new();

    emit_ownership_comment(entity, generator_version, &mut lines);
    lines.push(String::new());

    let title = entity
        .display_name
        .as_deref()
        .unwrap_or(entity.name.as_str());
    lines.push(format!("# {title}"));
    lines.push(String::new());

    if let Some(desc) = &entity.description {
        lines.push(desc.clone());
        lines.push(String::new());
    }

    if !entity.tags.is_empty() {
        let tags = entity.tags.join(", ");
        lines.push(format!("**Tags:** {tags}"));
        lines.push(String::new());
    }

    if let Some(domain) = &entity.domain {
        lines.push(format!("**Domain:** {domain}"));
        lines.push(String::new());
    }

    if let Some(entity_type) = &entity.entity_type {
        lines.push(format!("**Entity type:** {entity_type}"));
        lines.push(String::new());
    }

    if !entity.business_key.is_empty() {
        let keys = entity
            .business_key
            .iter()
            .map(|k| format!("`{k}`"))
            .collect::<Vec<_>>()
            .join(", ");
        lines.push(format!("**Business key:** {keys}"));
        lines.push(String::new());
    }

    emit_attribute_table(&entity.attributes, &mut lines);

    lines.push(String::new());

    let mut metadata_ids = vec![entity.id.clone()];
    metadata_ids.extend(entity.attributes.iter().map(|a| a.id.clone()));

    ArtifactDescriptor {
        path: format!("docs/entities/{}.md", entity.name),
        kind: ArtifactKind::MarkdownDoc,
        artifact_id: format!("art_docs_{}", entity.name),
        generator: GENERATOR_NAME.into(),
        generator_version: generator_version.to_owned(),
        content: lines.join("\n"),
        metadata_object_ids: metadata_ids,
    }
}

fn emit_ownership_comment(entity: &ContractEntity, version: &str, lines: &mut Vec<String>) {
    lines.push(format!(
        "<!-- Generated by know-now. Artifact ID: art_docs_{}. Generator: {GENERATOR_NAME}. Version: {version}. Do not edit directly unless you intend to fork this artifact. -->",
        entity.name
    ));
}

fn emit_attribute_table(attributes: &[ContractAttribute], lines: &mut Vec<String>) {
    if attributes.is_empty() {
        return;
    }

    lines.push("## Attributes".to_owned());
    lines.push(String::new());
    lines.push("| Name | Logical Type | Semantic Type | Required | Description |".to_owned());
    lines.push("|------|-------------|--------------|----------|-------------|".to_owned());

    for attr in attributes {
        let logical = attr.logical_type.as_deref().unwrap_or("-");
        let semantic = attr.semantic_type.as_deref().unwrap_or("-");
        let required = if attr.required.unwrap_or(false) {
            "Yes"
        } else {
            "No"
        };
        let desc = attr.description.as_deref().unwrap_or("-");
        lines.push(format!(
            "| {name} | {logical} | {semantic} | {required} | {desc} |",
            name = attr.name
        ));
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use know_now_contract::contract::{ContractAttribute, ContractEntity, ContractTrace};

    fn minimal_contract() -> GeneratorContract {
        GeneratorContract {
            contract_version: "1.0".into(),
            project: None,
            target_database: None,
            entities: vec![ContractEntity {
                id: "ent_customer".into(),
                name: "customer".into(),
                display_name: Some("Customer".into()),
                domain: Some("sales".into()),
                module: None,
                owner: None,
                steward: None,
                classification: None,
                retention_policy: None,
                description: Some("Core customer entity for the sales domain.".into()),
                entity_type: Some("dimension".into()),
                tags: vec!["core".into(), "pii".into()],
                business_key: vec!["email".into()],
                attributes: vec![
                    ContractAttribute {
                        id: "attr_customer_id".into(),
                        name: "id".into(),
                        logical_type: Some("integer".into()),
                        semantic_type: None,
                        sensitivity: None,
                        pii: None,
                        required: Some(true),
                        is_unique: Some(true),
                        constraints: vec![],
                        description: Some("Primary surrogate key.".into()),
                        attr_type: None,
                    },
                    ContractAttribute {
                        id: "attr_customer_email".into(),
                        name: "email".into(),
                        logical_type: Some("string".into()),
                        semantic_type: Some("email".into()),
                        sensitivity: None,
                        pii: Some(true),
                        required: None,
                        is_unique: None,
                        constraints: vec![],
                        description: None,
                        attr_type: None,
                    },
                ],
            }],
            relationships: vec![],
            source_systems: vec![],
            quality_rules: vec![],
            governance: None,
            open_questions: vec![],
            assumptions: vec![],
            trace: ContractTrace::default(),
        }
    }

    #[test]
    fn generates_entity_page() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        assert_eq!(artifacts.len(), 1);
        assert_eq!(artifacts[0].path, "docs/entities/customer.md");
        assert_eq!(artifacts[0].kind, ArtifactKind::MarkdownDoc);
    }

    #[test]
    fn ownership_comment_present() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let content = &artifacts[0].content;
        assert!(content.starts_with("<!-- Generated by know-now."));
        assert!(content.contains("art_docs_customer"));
        assert!(content.contains(GENERATOR_NAME));
        assert!(content.contains("Do not edit directly"));
    }

    #[test]
    fn title_uses_display_name() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        assert!(artifacts[0].content.contains("# Customer"));
    }

    #[test]
    fn title_falls_back_to_name() {
        let gen = DocsGenerator::new();
        let mut contract = minimal_contract();
        contract.entities[0].display_name = None;
        let artifacts = gen.generate(&contract).unwrap();
        assert!(artifacts[0].content.contains("# customer"));
    }

    #[test]
    fn description_present() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        assert!(artifacts[0]
            .content
            .contains("Core customer entity for the sales domain."));
    }

    #[test]
    fn domain_shown() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        assert!(artifacts[0].content.contains("**Domain:** sales"));
    }

    #[test]
    fn entity_type_shown() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        assert!(artifacts[0].content.contains("**Entity type:** dimension"));
    }

    #[test]
    fn tags_shown() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        assert!(artifacts[0].content.contains("**Tags:** core, pii"));
    }

    #[test]
    fn business_key_shown() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        assert!(artifacts[0].content.contains("**Business key:** `email`"));
    }

    #[test]
    fn attribute_table_present() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let content = &artifacts[0].content;
        assert!(content.contains("## Attributes"));
        assert!(
            content.contains("| Name | Logical Type | Semantic Type | Required | Description |")
        );
        assert!(content.contains("| id | integer | - | Yes | Primary surrogate key. |"));
        assert!(content.contains("| email | string | email | No | - |"));
    }

    #[test]
    fn metadata_ids_collected() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let ids = &artifacts[0].metadata_object_ids;
        assert!(ids.contains(&"ent_customer".to_owned()));
        assert!(ids.contains(&"attr_customer_id".to_owned()));
        assert!(ids.contains(&"attr_customer_email".to_owned()));
    }

    #[test]
    fn deterministic_output() {
        let gen = DocsGenerator::new();
        let contract = minimal_contract();
        let a = gen.generate(&contract).unwrap();
        let b = gen.generate(&contract).unwrap();
        assert_eq!(a[0].content, b[0].content);
    }

    #[test]
    fn no_crlf_in_output() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        assert!(!artifacts[0].content.contains('\r'), "NFR-PO3: LF only");
    }

    #[test]
    fn no_html_beyond_comments() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let content = &artifacts[0].content;
        for line in content.lines() {
            if line.starts_with("<!--") {
                continue;
            }
            assert!(
                !line.contains('<'),
                "no HTML beyond ownership comment: {line}"
            );
        }
    }

    #[test]
    fn no_timestamps() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let content = &artifacts[0].content;
        assert!(!content.contains("2026"));
        assert!(!content.contains("timestamp"));
        assert!(!content.contains("Generated at"));
    }

    #[test]
    fn multiple_entities_sorted_by_path() {
        let gen = DocsGenerator::new();
        let mut contract = minimal_contract();
        contract.entities.push(ContractEntity {
            id: "ent_account".into(),
            name: "account".into(),
            display_name: None,
            domain: None,
            module: None,
            owner: None,
            steward: None,
            classification: None,
            retention_policy: None,
            description: None,
            entity_type: None,
            tags: vec![],
            business_key: vec![],
            attributes: vec![],
        });
        let artifacts = gen.generate(&contract).unwrap();
        assert_eq!(artifacts.len(), 2);
        assert_eq!(artifacts[0].path, "docs/entities/account.md");
        assert_eq!(artifacts[1].path, "docs/entities/customer.md");
    }

    #[test]
    fn empty_contract_produces_no_artifacts() {
        let gen = DocsGenerator::new();
        let contract = GeneratorContract {
            contract_version: "1.0".into(),
            project: None,
            target_database: None,
            entities: vec![],
            relationships: vec![],
            source_systems: vec![],
            quality_rules: vec![],
            governance: None,
            open_questions: vec![],
            assumptions: vec![],
            trace: ContractTrace::default(),
        };
        let artifacts = gen.generate(&contract).unwrap();
        assert!(artifacts.is_empty());
    }

    #[test]
    fn entity_without_attributes_skips_table() {
        let gen = DocsGenerator::new();
        let contract = GeneratorContract {
            contract_version: "1.0".into(),
            project: None,
            target_database: None,
            entities: vec![ContractEntity {
                id: "ent_empty".into(),
                name: "empty".into(),
                display_name: None,
                domain: None,
                module: None,
                owner: None,
                steward: None,
                classification: None,
                retention_policy: None,
                description: None,
                entity_type: None,
                tags: vec![],
                business_key: vec![],
                attributes: vec![],
            }],
            relationships: vec![],
            source_systems: vec![],
            quality_rules: vec![],
            governance: None,
            open_questions: vec![],
            assumptions: vec![],
            trace: ContractTrace::default(),
        };
        let artifacts = gen.generate(&contract).unwrap();
        assert!(!artifacts[0].content.contains("## Attributes"));
    }

    #[test]
    fn generator_is_send_sync() {
        fn assert_send_sync<T: Send + Sync>() {}
        assert_send_sync::<DocsGenerator>();
    }

    #[test]
    fn no_dep_on_metadata() {
        assert_eq!(DocsGenerator::new().name(), GENERATOR_NAME);
    }

    #[test]
    fn no_relative_links_in_output() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let content = &artifacts[0].content;
        assert!(
            !content.contains("]("),
            "no relative links in Phase 1 output"
        );
    }
}
