//! Markdown and Mermaid documentation generator crate for know-now.
//!
//! Responsibility is defined in PRD section 8.2 (workspace layout).

use know_now_codegen::artifact::{ArtifactDescriptor, ArtifactKind};
use know_now_codegen::generator::{GenerationError, Generator};
use know_now_contract::contract::{
    ContractAssumption, ContractAttribute, ContractEntity, ContractGovernance,
    ContractOpenQuestion, ContractRelationship, ContractSourceSystem, GeneratorContract,
};

mod phrases;

const GENERATOR_NAME: &str = "know_now_gen_docs";

pub struct DocsGenerator {
    version: String,
}

impl DocsGenerator {
    #[must_use]
    pub fn new() -> Self {
        Self {
            version: env!("CARGO_PKG_VERSION").to_owned(),
        }
    }
}

impl Default for DocsGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for DocsGenerator {
    fn name(&self) -> &str {
        GENERATOR_NAME
    }

    fn version(&self) -> &str {
        &self.version
    }

    fn generate(
        &self,
        contract: &GeneratorContract,
    ) -> Result<Vec<ArtifactDescriptor>, Vec<GenerationError>> {
        let mut artifacts = Vec::new();

        if !contract.entities.is_empty() {
            artifacts.push(generate_overview(contract, &self.version));
        }

        for entity in &contract.entities {
            artifacts.push(generate_entity_page(entity, contract, &self.version));
        }

        artifacts.sort_by(|a, b| a.path.cmp(&b.path));
        Ok(artifacts)
    }
}

fn generate_overview(contract: &GeneratorContract, generator_version: &str) -> ArtifactDescriptor {
    let mut lines: Vec<String> = Vec::new();

    lines.push(format!(
        "<!-- Generated by know-now. Artifact ID: art_docs_overview. Generator: {GENERATOR_NAME}. Version: {generator_version}. Do not edit directly unless you intend to fork this artifact. -->"
    ));
    lines.push(String::new());

    let title = contract
        .project
        .as_ref()
        .map_or("Project Documentation", |p| p.name.as_str());
    lines.push(format!("# {title}"));
    lines.push(String::new());

    if let Some(ref proj) = contract.project {
        if let Some(ref desc) = proj.description {
            lines.push(desc.clone());
            lines.push(String::new());
        }
        if let Some(ref owner) = proj.owner {
            lines.push(format!("**Owner:** {owner}"));
            lines.push(String::new());
        }
    }

    emit_entity_index(&contract.entities, &mut lines);

    lines.push(String::new());

    let mut metadata_ids: Vec<String> = vec![];
    if let Some(ref proj) = contract.project {
        metadata_ids.push(proj.name.clone());
    }

    ArtifactDescriptor {
        path: "docs/README.md".to_owned(),
        kind: ArtifactKind::MarkdownDoc,
        artifact_id: "art_docs_overview".to_owned(),
        generator: GENERATOR_NAME.into(),
        generator_version: generator_version.to_owned(),
        content: lines.join("\n"),
        metadata_object_ids: metadata_ids,
    }
}

fn emit_entity_index(entities: &[ContractEntity], lines: &mut Vec<String>) {
    lines.push("## Entities".to_owned());
    lines.push(String::new());

    let mut domains: std::collections::BTreeMap<String, Vec<&ContractEntity>> =
        std::collections::BTreeMap::new();
    let mut no_domain: Vec<&ContractEntity> = Vec::new();

    for entity in entities {
        if let Some(ref domain) = entity.domain {
            domains.entry(domain.clone()).or_default().push(entity);
        } else {
            no_domain.push(entity);
        }
    }

    if !domains.is_empty() {
        for (domain, domain_entities) in &domains {
            lines.push(format!("### {domain}"));
            lines.push(String::new());
            for entity in domain_entities {
                let title = entity
                    .display_name
                    .as_deref()
                    .unwrap_or(entity.name.as_str());
                lines.push(format!("- [{title}](entities/{}.md)", entity.name));
            }
            lines.push(String::new());
        }
    }

    if !no_domain.is_empty() {
        if !domains.is_empty() {
            lines.push("### Other".to_owned());
            lines.push(String::new());
        }
        for entity in &no_domain {
            let title = entity
                .display_name
                .as_deref()
                .unwrap_or(entity.name.as_str());
            lines.push(format!("- [{title}](entities/{}.md)", entity.name));
        }
        lines.push(String::new());
    }
}

fn generate_entity_page(
    entity: &ContractEntity,
    contract: &GeneratorContract,
    generator_version: &str,
) -> ArtifactDescriptor {
    let mut lines: Vec<String> = Vec::new();

    emit_ownership_comment(entity, generator_version, &mut lines);
    lines.push(String::new());

    let title = entity
        .display_name
        .as_deref()
        .unwrap_or(entity.name.as_str());
    lines.push(format!("# {title}"));
    lines.push(String::new());

    if let Some(desc) = &entity.description {
        lines.push(desc.clone());
        lines.push(String::new());
    }

    emit_entity_metadata(entity, &mut lines);
    emit_attribute_table(&entity.attributes, &mut lines);

    let entity_rels: Vec<&ContractRelationship> = contract
        .relationships
        .iter()
        .filter(|r| r.from_entity == entity.name || r.to_entity == entity.name)
        .collect();
    emit_relationships(&entity_rels, &entity.name, &mut lines);

    emit_source_mappings(&contract.source_systems, &entity.name, &mut lines);

    emit_governance(entity, contract.governance.as_ref(), &mut lines);

    let entity_questions: Vec<&ContractOpenQuestion> = contract
        .open_questions
        .iter()
        .filter(|q| q.entity.as_deref() == Some(&entity.name))
        .collect();
    emit_open_questions(&entity_questions, &mut lines);

    let entity_assumptions: Vec<&ContractAssumption> = contract
        .assumptions
        .iter()
        .filter(|a| a.entity.as_deref() == Some(&entity.name))
        .collect();
    emit_assumptions(&entity_assumptions, &mut lines);

    emit_quality_warnings(entity, &mut lines);

    lines.push(String::new());

    let mut metadata_ids = vec![entity.id.clone()];
    metadata_ids.extend(entity.attributes.iter().map(|a| a.id.clone()));
    for rel in &entity_rels {
        metadata_ids.push(rel.id.clone());
    }
    for q in &entity_questions {
        metadata_ids.push(q.id.clone());
    }
    for a in &entity_assumptions {
        metadata_ids.push(a.id.clone());
    }

    ArtifactDescriptor {
        path: format!("docs/entities/{}.md", entity.name),
        kind: ArtifactKind::MarkdownDoc,
        artifact_id: format!("art_docs_{}", entity.name),
        generator: GENERATOR_NAME.into(),
        generator_version: generator_version.to_owned(),
        content: lines.join("\n"),
        metadata_object_ids: metadata_ids,
    }
}

fn emit_ownership_comment(entity: &ContractEntity, version: &str, lines: &mut Vec<String>) {
    lines.push(format!(
        "<!-- Generated by know-now. Artifact ID: art_docs_{}. Generator: {GENERATOR_NAME}. Version: {version}. Do not edit directly unless you intend to fork this artifact. -->",
        entity.name
    ));
}

fn emit_entity_metadata(entity: &ContractEntity, lines: &mut Vec<String>) {
    if !entity.tags.is_empty() {
        let tags = entity.tags.join(", ");
        lines.push(format!("**Tags:** {tags}"));
        lines.push(String::new());
    }

    if let Some(domain) = &entity.domain {
        lines.push(format!("**Domain:** {domain}"));
        lines.push(String::new());
    }

    if let Some(entity_type) = &entity.entity_type {
        lines.push(format!("**Entity type:** {entity_type}"));
        lines.push(String::new());
    }

    if !entity.business_key.is_empty() {
        let keys = entity
            .business_key
            .iter()
            .map(|k| format!("`{k}`"))
            .collect::<Vec<_>>()
            .join(", ");
        lines.push(format!("**Business key:** {keys}"));
        lines.push(String::new());
    }
}

fn emit_attribute_table(attributes: &[ContractAttribute], lines: &mut Vec<String>) {
    if attributes.is_empty() {
        return;
    }

    lines.push("## Attributes".to_owned());
    lines.push(String::new());
    lines.push(
        "| Name | Logical Type | Semantic Type | Required | Unique | Constraints | Governance | Description |"
            .to_owned(),
    );
    lines.push(
        "|------|-------------|--------------|----------|--------|-------------|------------|-------------|"
            .to_owned(),
    );

    for attr in attributes {
        let logical = attr.logical_type.as_deref().unwrap_or("-");
        let semantic = attr.semantic_type.as_deref().unwrap_or("-");
        let required = if attr.required.unwrap_or(false) {
            "Yes"
        } else {
            "No"
        };
        let unique = if attr.is_unique.unwrap_or(false) {
            "Yes"
        } else {
            "-"
        };
        let constraints = if attr.constraints.is_empty() {
            "-".to_owned()
        } else {
            attr.constraints
                .iter()
                .map(|c| phrases::friendly_constraint(c))
                .collect::<Vec<_>>()
                .join("; ")
        };
        let governance = format_attr_governance(attr);
        let desc = attr.description.as_deref().unwrap_or("-");
        lines.push(format!(
            "| {name} | {logical} | {semantic} | {required} | {unique} | {constraints} | {governance} | {desc} |",
            name = attr.name
        ));
    }
}

fn format_attr_governance(attr: &ContractAttribute) -> String {
    let mut labels = Vec::new();
    if attr.pii == Some(true) {
        labels.push("PII");
    }
    if let Some(ref sensitivity) = attr.sensitivity {
        labels.push(sensitivity);
    }
    if labels.is_empty() {
        "-".to_owned()
    } else {
        labels.join(", ")
    }
}

fn emit_relationships(
    relationships: &[&ContractRelationship],
    entity_name: &str,
    lines: &mut Vec<String>,
) {
    if relationships.is_empty() {
        return;
    }

    lines.push(String::new());
    lines.push("## Relationships".to_owned());
    lines.push(String::new());

    let incoming: Vec<&&ContractRelationship> = relationships
        .iter()
        .filter(|r| r.to_entity == entity_name)
        .collect();
    let outgoing: Vec<&&ContractRelationship> = relationships
        .iter()
        .filter(|r| r.from_entity == entity_name)
        .collect();

    if !incoming.is_empty() {
        lines.push("### References to this entity".to_owned());
        lines.push(String::new());
        for rel in &incoming {
            let cardinality = rel.cardinality.as_deref().unwrap_or("related");
            let from_key = rel.from_key.as_deref().unwrap_or("?");
            let to_key = rel.to_key.as_deref().unwrap_or("?");
            lines.push(format!(
                "- [{from}]({from}.md) `{from_key}` -> `{to_key}` ({cardinality})",
                from = rel.from_entity,
            ));
        }
        lines.push(String::new());
    }

    if !outgoing.is_empty() {
        lines.push("### References from this entity".to_owned());
        lines.push(String::new());
        for rel in &outgoing {
            let cardinality = rel.cardinality.as_deref().unwrap_or("related");
            let from_key = rel.from_key.as_deref().unwrap_or("?");
            let to_key = rel.to_key.as_deref().unwrap_or("?");
            lines.push(format!(
                "- `{from_key}` -> [{to}]({to}.md) `{to_key}` ({cardinality})",
                to = rel.to_entity,
            ));
        }
        lines.push(String::new());
    }
}

fn emit_source_mappings(
    source_systems: &[ContractSourceSystem],
    entity_name: &str,
    lines: &mut Vec<String>,
) {
    let mapped_sources: Vec<(
        &ContractSourceSystem,
        &know_now_contract::contract::ContractSourceTable,
    )> = source_systems
        .iter()
        .flat_map(|sys| {
            sys.tables
                .iter()
                .filter(|t| t.entity.as_deref() == Some(entity_name))
                .map(move |t| (sys, t))
        })
        .collect();

    if mapped_sources.is_empty() {
        return;
    }

    lines.push(String::new());
    lines.push("## Source Mappings".to_owned());
    lines.push(String::new());

    for (sys, table) in &mapped_sources {
        let schema_prefix = table
            .schema
            .as_ref()
            .map_or(String::new(), |s| format!("{s}."));
        let kind = sys.kind.as_deref().unwrap_or("source");
        lines.push(format!(
            "### {name} ({kind}) — `{schema_prefix}{table_name}`",
            name = sys.name,
            table_name = table.name,
        ));
        lines.push(String::new());

        if !table.columns.is_empty() {
            lines.push("| Source Column | Target Attribute | Transform |".to_owned());
            lines.push("|--------------|-----------------|-----------|".to_owned());
            for col in &table.columns {
                let transform = col.transform.as_deref().unwrap_or("-");
                lines.push(format!(
                    "| {} | {} | {} |",
                    col.source, col.target, transform
                ));
            }
            lines.push(String::new());
        }
    }
}

fn emit_governance(
    entity: &ContractEntity,
    global_governance: Option<&ContractGovernance>,
    lines: &mut Vec<String>,
) {
    let owner = entity
        .owner
        .as_deref()
        .or_else(|| global_governance.and_then(|g| g.data_owner.as_deref()));
    let steward = entity
        .steward
        .as_deref()
        .or_else(|| global_governance.and_then(|g| g.data_steward.as_deref()));
    let classification = entity
        .classification
        .as_deref()
        .or_else(|| global_governance.and_then(|g| g.classification_default.as_deref()));
    let retention = entity
        .retention_policy
        .as_deref()
        .or_else(|| global_governance.and_then(|g| g.retention_default.as_deref()));

    if owner.is_none() && steward.is_none() && classification.is_none() && retention.is_none() {
        return;
    }

    lines.push(String::new());
    lines.push("## Governance".to_owned());
    lines.push(String::new());

    if let Some(owner) = owner {
        lines.push(format!("- **Data owner:** {owner}"));
    }
    if let Some(steward) = steward {
        lines.push(format!("- **Data steward:** {steward}"));
    }
    if let Some(classification) = classification {
        lines.push(format!(
            "- **Classification:** {}",
            phrases::friendly_classification(classification)
        ));
    }
    if let Some(retention) = retention {
        lines.push(format!("- **Retention policy:** {retention}"));
    }
    lines.push(String::new());
}

fn emit_open_questions(questions: &[&ContractOpenQuestion], lines: &mut Vec<String>) {
    if questions.is_empty() {
        return;
    }

    lines.push(String::new());
    lines.push("## Open Questions".to_owned());
    lines.push(String::new());

    for q in questions {
        let priority = q.priority.as_deref().unwrap_or("unspecified");
        lines.push(format!("- **[{priority}]** {}", q.question));
        if let Some(ref ctx) = q.context {
            lines.push(format!("  - Context: {ctx}"));
        }
    }
    lines.push(String::new());
}

fn emit_assumptions(assumptions: &[&ContractAssumption], lines: &mut Vec<String>) {
    if assumptions.is_empty() {
        return;
    }

    lines.push(String::new());
    lines.push("## Assumptions".to_owned());
    lines.push(String::new());

    for a in assumptions {
        let risk = a.risk.as_deref().unwrap_or("unspecified");
        lines.push(format!("- **[risk: {risk}]** {}", a.statement));
        if let Some(ref rationale) = a.rationale {
            lines.push(format!("  - Rationale: {rationale}"));
        }
    }
    lines.push(String::new());
}

fn emit_quality_warnings(entity: &ContractEntity, lines: &mut Vec<String>) {
    let mut warnings = Vec::new();

    if entity.description.is_none() {
        warnings.push(format!(
            "Entity `{}` is missing a description.",
            entity.name
        ));
    }

    for attr in &entity.attributes {
        if attr.description.is_none() {
            warnings.push(format!(
                "Attribute `{}.{}` is missing a description.",
                entity.name, attr.name
            ));
        }
    }

    if warnings.is_empty() {
        return;
    }

    lines.push(String::new());
    lines.push("## Documentation Quality".to_owned());
    lines.push(String::new());

    for w in &warnings {
        lines.push(format!("- {w}"));
    }
    lines.push(String::new());
}

#[cfg(test)]
mod tests {
    use super::*;
    use know_now_contract::contract::{
        ContractAssumption, ContractAttribute, ContractEntity, ContractGovernance,
        ContractOpenQuestion, ContractProject, ContractRelationship, ContractSourceColumn,
        ContractSourceSystem, ContractSourceTable, ContractTrace,
    };

    fn minimal_contract() -> GeneratorContract {
        GeneratorContract {
            contract_version: "1.0".into(),
            project: None,
            target_database: None,
            entities: vec![ContractEntity {
                id: "ent_customer".into(),
                name: "customer".into(),
                display_name: Some("Customer".into()),
                domain: Some("sales".into()),
                module: None,
                owner: None,
                steward: None,
                classification: None,
                retention_policy: None,
                description: Some("Core customer entity for the sales domain.".into()),
                entity_type: Some("dimension".into()),
                tags: vec!["core".into(), "pii".into()],
                business_key: vec!["email".into()],
                attributes: vec![
                    ContractAttribute {
                        id: "attr_customer_id".into(),
                        name: "id".into(),
                        logical_type: Some("integer".into()),
                        semantic_type: None,
                        sensitivity: None,
                        pii: None,
                        required: Some(true),
                        is_unique: Some(true),
                        constraints: vec![],
                        description: Some("Primary surrogate key.".into()),
                        attr_type: None,
                    },
                    ContractAttribute {
                        id: "attr_customer_email".into(),
                        name: "email".into(),
                        logical_type: Some("string".into()),
                        semantic_type: Some("email".into()),
                        sensitivity: None,
                        pii: Some(true),
                        required: None,
                        is_unique: None,
                        constraints: vec![],
                        description: None,
                        attr_type: None,
                    },
                ],
            }],
            relationships: vec![],
            source_systems: vec![],
            quality_rules: vec![],
            governance: None,
            open_questions: vec![],
            assumptions: vec![],
            trace: ContractTrace::default(),
        }
    }

    fn rich_contract() -> GeneratorContract {
        let mut contract = minimal_contract();
        contract.project = Some(ContractProject {
            name: "Demo Project".into(),
            description: Some("A demonstration project.".into()),
            owner: Some("data-team".into()),
            tags: vec!["demo".into()],
        });
        contract.relationships = vec![ContractRelationship {
            id: "rel_order_customer".into(),
            from_entity: "order".into(),
            to_entity: "customer".into(),
            cardinality: Some("many_to_one".into()),
            from_key: Some("customer_id".into()),
            to_key: Some("id".into()),
            description: None,
        }];
        contract.source_systems = vec![ContractSourceSystem {
            name: "crm_db".into(),
            kind: Some("database".into()),
            description: None,
            tables: vec![ContractSourceTable {
                name: "customers".into(),
                entity: Some("customer".into()),
                schema: Some("public".into()),
                columns: vec![
                    ContractSourceColumn {
                        source: "cust_email".into(),
                        target: "email".into(),
                        transform: Some("LOWER(cust_email)".into()),
                    },
                    ContractSourceColumn {
                        source: "cust_id".into(),
                        target: "id".into(),
                        transform: None,
                    },
                ],
            }],
        }];
        contract.governance = Some(ContractGovernance {
            data_owner: Some("analytics-team".into()),
            data_steward: Some("jane@example.com".into()),
            classification_default: Some("internal".into()),
            retention_default: Some("3 years".into()),
        });
        contract.open_questions = vec![ContractOpenQuestion {
            id: "q_email_validation".into(),
            question: "Should email addresses be validated against DNS?".into(),
            context: Some("Currently only format validation is applied.".into()),
            entity: Some("customer".into()),
            priority: Some("medium".into()),
        }];
        contract.assumptions = vec![ContractAssumption {
            id: "a_email_unique".into(),
            statement: "Email addresses are unique per customer.".into(),
            rationale: Some("Business rule confirmed by product team.".into()),
            entity: Some("customer".into()),
            risk: Some("low".into()),
        }];
        contract
    }

    #[test]
    fn generates_entity_page() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        assert!(artifacts
            .iter()
            .any(|a| a.path == "docs/entities/customer.md"));
    }

    #[test]
    fn generates_overview_page() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        assert!(artifacts.iter().any(|a| a.path == "docs/README.md"));
    }

    #[test]
    fn empty_contract_produces_no_artifacts() {
        let gen = DocsGenerator::new();
        let contract = GeneratorContract {
            contract_version: "1.0".into(),
            project: None,
            target_database: None,
            entities: vec![],
            relationships: vec![],
            source_systems: vec![],
            quality_rules: vec![],
            governance: None,
            open_questions: vec![],
            assumptions: vec![],
            trace: ContractTrace::default(),
        };
        let artifacts = gen.generate(&contract).unwrap();
        assert!(artifacts.is_empty());
    }

    #[test]
    fn overview_lists_entities_with_links() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let overview = artifacts
            .iter()
            .find(|a| a.path == "docs/README.md")
            .unwrap();
        assert!(overview
            .content
            .contains("[Customer](entities/customer.md)"));
    }

    #[test]
    fn overview_groups_by_domain() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let overview = artifacts
            .iter()
            .find(|a| a.path == "docs/README.md")
            .unwrap();
        assert!(overview.content.contains("### sales"));
    }

    #[test]
    fn overview_shows_project_info() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&rich_contract()).unwrap();
        let overview = artifacts
            .iter()
            .find(|a| a.path == "docs/README.md")
            .unwrap();
        assert!(overview.content.contains("# Demo Project"));
        assert!(overview.content.contains("A demonstration project."));
        assert!(overview.content.contains("**Owner:** data-team"));
    }

    #[test]
    fn ownership_comment_present() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let entity = artifacts
            .iter()
            .find(|a| a.path.contains("customer"))
            .unwrap();
        assert!(entity.content.starts_with("<!-- Generated by know-now."));
        assert!(entity.content.contains("art_docs_customer"));
    }

    #[test]
    fn title_uses_display_name() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let entity = artifacts
            .iter()
            .find(|a| a.path.contains("customer"))
            .unwrap();
        assert!(entity.content.contains("# Customer"));
    }

    #[test]
    fn title_falls_back_to_name() {
        let gen = DocsGenerator::new();
        let mut contract = minimal_contract();
        contract.entities[0].display_name = None;
        let artifacts = gen.generate(&contract).unwrap();
        let entity = artifacts
            .iter()
            .find(|a| a.path.contains("customer"))
            .unwrap();
        assert!(entity.content.contains("# customer"));
    }

    #[test]
    fn description_present() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let entity = artifacts
            .iter()
            .find(|a| a.path.contains("customer"))
            .unwrap();
        assert!(entity.content.contains("Core customer entity"));
    }

    #[test]
    fn domain_shown() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let entity = artifacts
            .iter()
            .find(|a| a.path.contains("customer"))
            .unwrap();
        assert!(entity.content.contains("**Domain:** sales"));
    }

    #[test]
    fn tags_shown() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let entity = artifacts
            .iter()
            .find(|a| a.path.contains("customer"))
            .unwrap();
        assert!(entity.content.contains("**Tags:** core, pii"));
    }

    #[test]
    fn business_key_shown() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let entity = artifacts
            .iter()
            .find(|a| a.path.contains("customer"))
            .unwrap();
        assert!(entity.content.contains("**Business key:** `email`"));
    }

    #[test]
    fn attribute_table_extended() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let entity = artifacts
            .iter()
            .find(|a| a.path.contains("customer"))
            .unwrap();
        assert!(entity.content.contains("| Name | Logical Type | Semantic Type | Required | Unique | Constraints | Governance | Description |"));
        assert!(entity.content.contains("| id | integer | - | Yes | Yes |"));
        assert!(entity
            .content
            .contains("| email | string | email | No | - | - | PII |"));
    }

    #[test]
    fn relationships_section() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&rich_contract()).unwrap();
        let entity = artifacts
            .iter()
            .find(|a| a.path.contains("customer"))
            .unwrap();
        assert!(entity.content.contains("## Relationships"));
        assert!(entity.content.contains("[order](order.md)"));
        assert!(entity.content.contains("many_to_one"));
    }

    #[test]
    fn source_mappings_section() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&rich_contract()).unwrap();
        let entity = artifacts
            .iter()
            .find(|a| a.path.contains("customer"))
            .unwrap();
        assert!(entity.content.contains("## Source Mappings"));
        assert!(entity.content.contains("crm_db"));
        assert!(entity.content.contains("public.customers"));
        assert!(entity.content.contains("cust_email"));
        assert!(entity.content.contains("LOWER(cust_email)"));
    }

    #[test]
    fn governance_section() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&rich_contract()).unwrap();
        let entity = artifacts
            .iter()
            .find(|a| a.path.contains("customer"))
            .unwrap();
        assert!(entity.content.contains("## Governance"));
        assert!(entity.content.contains("analytics-team"));
        assert!(entity.content.contains("jane@example.com"));
    }

    #[test]
    fn open_questions_section() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&rich_contract()).unwrap();
        let entity = artifacts
            .iter()
            .find(|a| a.path.contains("customer"))
            .unwrap();
        assert!(entity.content.contains("## Open Questions"));
        assert!(entity.content.contains("[medium]"));
        assert!(entity.content.contains("email addresses be validated"));
    }

    #[test]
    fn assumptions_section() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&rich_contract()).unwrap();
        let entity = artifacts
            .iter()
            .find(|a| a.path.contains("customer"))
            .unwrap();
        assert!(entity.content.contains("## Assumptions"));
        assert!(entity.content.contains("[risk: low]"));
        assert!(entity.content.contains("Email addresses are unique"));
    }

    #[test]
    fn quality_warnings_for_missing_description() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let entity = artifacts
            .iter()
            .find(|a| a.path.contains("customer"))
            .unwrap();
        assert!(entity.content.contains("## Documentation Quality"));
        assert!(entity
            .content
            .contains("`customer.email` is missing a description"));
    }

    #[test]
    fn no_quality_warnings_when_complete() {
        let gen = DocsGenerator::new();
        let mut contract = minimal_contract();
        contract.entities[0].attributes[1].description = Some("Email address.".into());
        let artifacts = gen.generate(&contract).unwrap();
        let entity = artifacts
            .iter()
            .find(|a| a.path.contains("customer"))
            .unwrap();
        assert!(!entity.content.contains("## Documentation Quality"));
    }

    #[test]
    fn metadata_ids_include_relationships_and_questions() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&rich_contract()).unwrap();
        let entity = artifacts
            .iter()
            .find(|a| a.path.contains("customer"))
            .unwrap();
        assert!(entity
            .metadata_object_ids
            .contains(&"ent_customer".to_owned()));
        assert!(entity
            .metadata_object_ids
            .contains(&"rel_order_customer".to_owned()));
        assert!(entity
            .metadata_object_ids
            .contains(&"q_email_validation".to_owned()));
        assert!(entity
            .metadata_object_ids
            .contains(&"a_email_unique".to_owned()));
    }

    #[test]
    fn deterministic_output() {
        let gen = DocsGenerator::new();
        let contract = rich_contract();
        let a = gen.generate(&contract).unwrap();
        let b = gen.generate(&contract).unwrap();
        for (x, y) in a.iter().zip(b.iter()) {
            assert_eq!(x.content, y.content);
        }
    }

    #[test]
    fn no_crlf_in_output() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&rich_contract()).unwrap();
        for artifact in &artifacts {
            assert!(!artifact.content.contains('\r'), "NFR-PO3: LF only");
        }
    }

    #[test]
    fn no_html_beyond_comments() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&rich_contract()).unwrap();
        for artifact in &artifacts {
            for line in artifact.content.lines() {
                if line.starts_with("<!--") {
                    continue;
                }
                assert!(
                    !line.contains('<'),
                    "no HTML beyond ownership comment: {line}"
                );
            }
        }
    }

    #[test]
    fn no_timestamps() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&rich_contract()).unwrap();
        for artifact in &artifacts {
            assert!(!artifact.content.contains("2026"));
            assert!(!artifact.content.contains("timestamp"));
            assert!(!artifact.content.contains("Generated at"));
        }
    }

    #[test]
    fn multiple_entities_sorted_by_path() {
        let gen = DocsGenerator::new();
        let mut contract = minimal_contract();
        contract.entities.push(ContractEntity {
            id: "ent_account".into(),
            name: "account".into(),
            display_name: None,
            domain: None,
            module: None,
            owner: None,
            steward: None,
            classification: None,
            retention_policy: None,
            description: None,
            entity_type: None,
            tags: vec![],
            business_key: vec![],
            attributes: vec![],
        });
        let artifacts = gen.generate(&contract).unwrap();
        let paths: Vec<&str> = artifacts.iter().map(|a| a.path.as_str()).collect();
        assert_eq!(paths[0], "docs/README.md");
        assert_eq!(paths[1], "docs/entities/account.md");
        assert_eq!(paths[2], "docs/entities/customer.md");
    }

    #[test]
    fn entity_without_attributes_skips_table() {
        let gen = DocsGenerator::new();
        let contract = GeneratorContract {
            contract_version: "1.0".into(),
            project: None,
            target_database: None,
            entities: vec![ContractEntity {
                id: "ent_empty".into(),
                name: "empty".into(),
                display_name: None,
                domain: None,
                module: None,
                owner: None,
                steward: None,
                classification: None,
                retention_policy: None,
                description: None,
                entity_type: None,
                tags: vec![],
                business_key: vec![],
                attributes: vec![],
            }],
            relationships: vec![],
            source_systems: vec![],
            quality_rules: vec![],
            governance: None,
            open_questions: vec![],
            assumptions: vec![],
            trace: ContractTrace::default(),
        };
        let artifacts = gen.generate(&contract).unwrap();
        let entity = artifacts.iter().find(|a| a.path.contains("empty")).unwrap();
        assert!(!entity.content.contains("## Attributes"));
    }

    #[test]
    fn generator_is_send_sync() {
        fn assert_send_sync<T: Send + Sync>() {}
        assert_send_sync::<DocsGenerator>();
    }

    #[test]
    fn entity_links_use_relative_paths() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&rich_contract()).unwrap();
        let entity = artifacts
            .iter()
            .find(|a| a.path.contains("customer"))
            .unwrap();
        assert!(
            entity.content.contains("](order.md)"),
            "relationship links should use relative paths"
        );
    }

    #[test]
    fn overview_links_use_relative_paths() {
        let gen = DocsGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let overview = artifacts
            .iter()
            .find(|a| a.path == "docs/README.md")
            .unwrap();
        assert!(
            overview.content.contains("](entities/customer.md)"),
            "overview links should point to entities/"
        );
    }

    #[test]
    fn entity_governance_inherits_from_global() {
        let gen = DocsGenerator::new();
        let mut contract = minimal_contract();
        contract.governance = Some(ContractGovernance {
            data_owner: Some("global-owner".into()),
            data_steward: None,
            classification_default: Some("confidential".into()),
            retention_default: None,
        });
        let artifacts = gen.generate(&contract).unwrap();
        let entity = artifacts
            .iter()
            .find(|a| a.path.contains("customer"))
            .unwrap();
        assert!(entity.content.contains("## Governance"));
        assert!(entity.content.contains("global-owner"));
        assert!(entity.content.contains("Confidential"));
    }

    #[test]
    fn entity_governance_overrides_global() {
        let gen = DocsGenerator::new();
        let mut contract = minimal_contract();
        contract.entities[0].owner = Some("entity-owner".into());
        contract.governance = Some(ContractGovernance {
            data_owner: Some("global-owner".into()),
            data_steward: None,
            classification_default: None,
            retention_default: None,
        });
        let artifacts = gen.generate(&contract).unwrap();
        let entity = artifacts
            .iter()
            .find(|a| a.path.contains("customer"))
            .unwrap();
        assert!(entity.content.contains("entity-owner"));
        assert!(!entity.content.contains("global-owner"));
    }
}
