//! dbt project generator crate for know-now.
//!
//! Produces a complete dbt project: `dbt_project.yml`, `sources.yml`,
//! staging models, mart models, and `schema.yml` for each layer.

use know_now_codegen::artifact::{ArtifactDescriptor, ArtifactKind};
use know_now_codegen::generator::{GenerationError, Generator};
use know_now_contract::contract::{
    ContractAttribute, ContractEntity, ContractRelationship, ContractSourceSystem, GeneratorContract,
};

const GENERATOR_NAME: &str = "know_now_gen_dbt";

pub struct DbtGenerator {
    version: String,
}

impl DbtGenerator {
    #[must_use]
    pub fn new() -> Self {
        Self {
            version: env!("CARGO_PKG_VERSION").to_owned(),
        }
    }
}

impl Default for DbtGenerator {
    fn default() -> Self {
        Self::new()
    }
}

impl Generator for DbtGenerator {
    fn name(&self) -> &str {
        GENERATOR_NAME
    }

    fn version(&self) -> &str {
        &self.version
    }

    fn generate(
        &self,
        contract: &GeneratorContract,
    ) -> Result<Vec<ArtifactDescriptor>, Vec<GenerationError>> {
        if contract.entities.is_empty() {
            return Ok(vec![]);
        }

        let mut artifacts = Vec::new();
        let project_name = contract
            .project
            .as_ref()
            .map_or("know_now_project", |p| p.name.as_str());

        artifacts.push(emit_dbt_project_yml(project_name, &self.version));

        if !contract.source_systems.is_empty() {
            artifacts.push(emit_sources_yml(
                &contract.source_systems,
                &self.version,
            ));

            for source in &contract.source_systems {
                for table in &source.tables {
                    artifacts.push(emit_staging_model(source, table, &self.version));
                }
            }

            artifacts.push(emit_staging_schema_yml(
                &contract.source_systems,
                &self.version,
            ));
        }

        for entity in &contract.entities {
            artifacts.push(emit_mart_model(entity, &contract.relationships, &self.version));
        }

        artifacts.push(emit_marts_schema_yml(
            &contract.entities,
            &contract.relationships,
            &self.version,
        ));

        let generic_tests = emit_generic_tests(&contract.entities, &self.version);
        artifacts.extend(generic_tests);

        artifacts.sort_by(|a, b| a.path.cmp(&b.path));
        Ok(artifacts)
    }
}

fn ownership_comment(artifact_id: &str, version: &str) -> String {
    format!("-- Generated by know-now. Artifact ID: {artifact_id}. Generator: {GENERATOR_NAME}. Version: {version}. Do not edit directly unless you intend to fork this artifact.")
}

fn yaml_ownership_comment(artifact_id: &str, version: &str) -> String {
    format!("# Generated by know-now. Artifact ID: {artifact_id}. Generator: {GENERATOR_NAME}. Version: {version}. Do not edit directly unless you intend to fork this artifact.")
}

fn emit_dbt_project_yml(project_name: &str, version: &str) -> ArtifactDescriptor {
    let safe_name = project_name
        .chars()
        .map(|c| if c.is_alphanumeric() || c == '_' { c } else { '_' })
        .collect::<String>();

    let content = format!(
        "{comment}

name: '{safe_name}'
version: '1.0.0'
config-version: 2
profile: '{safe_name}'

model-paths:
  - models
  - ../../../custom/dbt/models

macro-paths:
  - ../../../custom/dbt/macros

seed-paths:
  - ../../../custom/dbt/seeds

test-paths:
  - tests

clean-targets:
  - target
  - dbt_packages
",
        comment = yaml_ownership_comment("art_dbt_project_yml", version),
    );

    ArtifactDescriptor {
        path: "dbt/dbt_project.yml".into(),
        kind: ArtifactKind::DbtModel,
        artifact_id: "art_dbt_project_yml".into(),
        generator: GENERATOR_NAME.into(),
        generator_version: version.to_owned(),
        content,
        metadata_object_ids: vec![],
    }
}

fn emit_sources_yml(
    sources: &[ContractSourceSystem],
    version: &str,
) -> ArtifactDescriptor {
    let mut lines = vec![
        yaml_ownership_comment("art_dbt_sources", version),
        String::new(),
        "version: 2".to_owned(),
        String::new(),
        "sources:".to_owned(),
    ];

    let mut sorted_sources: Vec<&ContractSourceSystem> = sources.iter().collect();
    sorted_sources.sort_by_key(|s| &s.name);

    for source in sorted_sources {
        lines.push(format!("  - name: {}", source.name));
        if let Some(ref desc) = source.description {
            lines.push(format!("    description: \"{}\"", escape_yaml(desc)));
        }
        if let Some(schema) = source.tables.first().and_then(|t| t.schema.as_ref()) {
            lines.push(format!("    schema: {schema}"));
        }
        if !source.tables.is_empty() {
            lines.push("    tables:".to_owned());
            let mut sorted_tables = source.tables.clone();
            sorted_tables.sort_by(|a, b| a.name.cmp(&b.name));
            for table in &sorted_tables {
                lines.push(format!("      - name: {}", table.name));
                if let Some(ref entity) = table.entity {
                    lines.push(format!(
                        "        description: \"Source table for entity {entity}.\""
                    ));
                }
                if !table.columns.is_empty() {
                    lines.push("        columns:".to_owned());
                    for col in &table.columns {
                        lines.push(format!("          - name: {}", col.source));
                        if col.source != col.target {
                            lines.push(format!(
                                "            description: \"Maps to {}.\"",
                                col.target
                            ));
                        }
                    }
                }
            }
        }
    }

    lines.push(String::new());

    let ids: Vec<String> = sources
        .iter()
        .flat_map(|s| s.tables.iter().filter_map(|t| t.entity.clone()))
        .collect();

    ArtifactDescriptor {
        path: "dbt/models/sources.yml".into(),
        kind: ArtifactKind::DbtSchema,
        artifact_id: "art_dbt_sources".into(),
        generator: GENERATOR_NAME.into(),
        generator_version: version.to_owned(),
        content: lines.join("\n"),
        metadata_object_ids: ids,
    }
}

fn emit_staging_model(
    source: &ContractSourceSystem,
    table: &know_now_contract::contract::ContractSourceTable,
    version: &str,
) -> ArtifactDescriptor {
    let model_name = format!("stg_{}_{}", source.name, table.name);
    let mut lines = Vec::new();

    lines.push(ownership_comment(&format!("art_dbt_{model_name}"), version));
    lines.push(String::new());

    lines.push("with source as (".to_owned());
    lines.push(String::new());
    lines.push(format!(
        "    select * from {{{{ source('{}', '{}') }}}}",
        source.name, table.name
    ));
    lines.push(String::new());
    lines.push(")".to_owned());
    lines.push(String::new());
    lines.push("select".to_owned());

    if table.columns.is_empty() {
        lines.push("    *".to_owned());
    } else {
        let last_idx = table.columns.len() - 1;
        for (idx, col) in table.columns.iter().enumerate() {
            let trailing = if idx < last_idx { "," } else { "" };
            if col.source == col.target || col.transform.is_none() {
                lines.push(format!("    {}{trailing}", col.source));
            } else if let Some(ref transform) = col.transform {
                lines.push(format!(
                    "    {transform} as {}{trailing}",
                    col.target
                ));
            }
        }
    }

    lines.push(String::new());
    lines.push("from source".to_owned());
    lines.push(String::new());

    let entity_id = table.entity.clone().unwrap_or_default();

    ArtifactDescriptor {
        path: format!("dbt/models/staging/{model_name}.sql"),
        kind: ArtifactKind::DbtModel,
        artifact_id: format!("art_dbt_{model_name}"),
        generator: GENERATOR_NAME.into(),
        generator_version: version.to_owned(),
        content: lines.join("\n"),
        metadata_object_ids: vec![entity_id],
    }
}

fn emit_staging_schema_yml(
    sources: &[ContractSourceSystem],
    version: &str,
) -> ArtifactDescriptor {
    let mut lines = vec![
        yaml_ownership_comment("art_dbt_staging_schema", version),
        String::new(),
        "version: 2".to_owned(),
        String::new(),
        "models:".to_owned(),
    ];

    let mut sorted_sources: Vec<&ContractSourceSystem> = sources.iter().collect();
    sorted_sources.sort_by_key(|s| &s.name);

    for source in sorted_sources {
        let mut sorted_tables = source.tables.clone();
        sorted_tables.sort_by(|a, b| a.name.cmp(&b.name));
        for table in &sorted_tables {
            let model_name = format!("stg_{}_{}", source.name, table.name);
            lines.push(format!("  - name: {model_name}"));
            if let Some(ref entity) = table.entity {
                lines.push(format!(
                    "    description: \"Staging model for entity {entity} from source {source_name}/{table_name}.\"",
                    source_name = source.name,
                    table_name = table.name,
                ));
            }
            if !table.columns.is_empty() {
                lines.push("    columns:".to_owned());
                for col in &table.columns {
                    lines.push(format!("      - name: {}", col.target));
                }
            }
        }
    }

    lines.push(String::new());

    ArtifactDescriptor {
        path: "dbt/models/staging/schema.yml".into(),
        kind: ArtifactKind::DbtSchema,
        artifact_id: "art_dbt_staging_schema".into(),
        generator: GENERATOR_NAME.into(),
        generator_version: version.to_owned(),
        content: lines.join("\n"),
        metadata_object_ids: vec![],
    }
}

fn emit_mart_model(
    entity: &ContractEntity,
    relationships: &[ContractRelationship],
    version: &str,
) -> ArtifactDescriptor {
    let mut lines = Vec::new();
    lines.push(ownership_comment(
        &format!("art_dbt_mart_{}", entity.name),
        version,
    ));
    lines.push(String::new());

    #[allow(clippy::suspicious_operation_groupings)]
    let incoming_joins: Vec<&ContractRelationship> = relationships
        .iter()
        .filter(|r| r.from_entity == entity.name && r.from_entity != r.to_entity)
        .collect();

    lines.push("select".to_owned());

    let attr_count = entity.attributes.len();
    for (idx, attr) in entity.attributes.iter().enumerate() {
        let trailing = if idx < attr_count - 1 || !incoming_joins.is_empty() {
            ","
        } else {
            ""
        };
        lines.push(format!("    base.{}{trailing}", attr.name));
    }

    for (idx, join) in incoming_joins.iter().enumerate() {
        let trailing = if idx < incoming_joins.len() - 1 { "," } else { "" };
        let alias = &join.to_entity;
        let to_key = join.to_key.as_deref().unwrap_or("id");
        lines.push(format!("    {alias}.{to_key} as {alias}_{to_key}{trailing}"));
    }

    lines.push(String::new());
    lines.push(format!("from {{{{ ref('{}') }}}} as base", entity.name));

    for join in &incoming_joins {
        let from_key = join.from_key.as_deref().unwrap_or("id");
        let to_key = join.to_key.as_deref().unwrap_or("id");
        lines.push(format!(
            "left join {{{{ ref('{}') }}}} as {} on base.{from_key} = {}.{to_key}",
            join.to_entity, join.to_entity, join.to_entity
        ));
    }

    lines.push(String::new());

    ArtifactDescriptor {
        path: format!("dbt/models/marts/{}.sql", entity.name),
        kind: ArtifactKind::DbtModel,
        artifact_id: format!("art_dbt_mart_{}", entity.name),
        generator: GENERATOR_NAME.into(),
        generator_version: version.to_owned(),
        content: lines.join("\n"),
        metadata_object_ids: vec![entity.id.clone()],
    }
}

fn emit_marts_schema_yml(
    entities: &[ContractEntity],
    relationships: &[ContractRelationship],
    version: &str,
) -> ArtifactDescriptor {
    let mut lines = vec![
        yaml_ownership_comment("art_dbt_marts_schema", version),
        String::new(),
        "version: 2".to_owned(),
        String::new(),
        "models:".to_owned(),
    ];

    let mut sorted: Vec<&ContractEntity> = entities.iter().collect();
    sorted.sort_by_key(|e| &e.name);

    for entity in sorted {
        lines.push(format!("  - name: {}", entity.name));
        if let Some(ref desc) = entity.description {
            lines.push(format!("    description: \"{}\"", escape_yaml(desc)));
        }
        if !entity.attributes.is_empty() {
            lines.push("    columns:".to_owned());
            for attr in &entity.attributes {
                emit_column_entry(attr, &entity.name, relationships, &mut lines);
            }
        }
    }

    lines.push(String::new());

    let ids: Vec<String> = entities.iter().map(|e| e.id.clone()).collect();

    ArtifactDescriptor {
        path: "dbt/models/marts/schema.yml".into(),
        kind: ArtifactKind::DbtSchema,
        artifact_id: "art_dbt_marts_schema".into(),
        generator: GENERATOR_NAME.into(),
        generator_version: version.to_owned(),
        content: lines.join("\n"),
        metadata_object_ids: ids,
    }
}

fn emit_column_entry(
    attr: &ContractAttribute,
    entity_name: &str,
    relationships: &[ContractRelationship],
    lines: &mut Vec<String>,
) {
    lines.push(format!("      - name: {}", attr.name));
    if let Some(ref desc) = attr.description {
        lines.push(format!("        description: \"{}\"", escape_yaml(desc)));
    }

    let mut simple_tests: Vec<&str> = Vec::new();
    let mut complex_tests: Vec<String> = Vec::new();

    if attr.required == Some(true) {
        simple_tests.push("not_null");
    }
    if attr.is_unique == Some(true) {
        simple_tests.push("unique");
    }

    if let Some(rel) = relationships.iter().find(|r| {
        r.from_entity == entity_name && r.from_key.as_deref() == Some(&attr.name)
    }) {
        let to_key = rel.to_key.as_deref().unwrap_or("id");
        complex_tests.push(format!(
            "          - relationships:\n              to: ref('{}')\n              field: {to_key}",
            rel.to_entity
        ));
    }

    match attr.semantic_type.as_deref() {
        Some("email") => simple_tests.push("is_valid_email"),
        Some("country_code") => {
            complex_tests.push(
                "          - accepted_values:\n              values: ['US', 'GB', 'DE', 'FR', 'NL', 'JP', 'AU', 'CA', 'BR', 'IN', 'SE', 'NO', 'DK', 'FI', 'ES', 'IT', 'CH', 'AT', 'BE', 'PT']".to_owned()
            );
        }
        Some("postal_code") => {
            complex_tests.push(
                "          - max_length:\n              max_value: 20".to_owned(),
            );
        }
        _ => {}
    }

    if let Some(max_len) = parse_constraint_value(&attr.constraints, "max_length") {
        complex_tests.push(format!(
            "          - max_length:\n              max_value: {max_len}"
        ));
    }

    if attr.semantic_type.as_deref() == Some("currency_amount") {
        if let Some(min) = parse_constraint_value(&attr.constraints, "minimum") {
            if min >= 0 {
                simple_tests.push("not_negative");
            }
        }
    }

    if !simple_tests.is_empty() || !complex_tests.is_empty() {
        lines.push("        tests:".to_owned());
        for test in simple_tests {
            lines.push(format!("          - {test}"));
        }
        for test in complex_tests {
            lines.push(test);
        }
    }
}

fn parse_constraint_value(constraints: &[String], key: &str) -> Option<i64> {
    let prefix = format!("{key}:");
    constraints
        .iter()
        .find(|c| c.starts_with(&prefix))
        .and_then(|c| c[prefix.len()..].trim().parse().ok())
}

fn needs_generic_test(entities: &[ContractEntity], test_name: &str) -> bool {
    entities.iter().any(|e| {
        e.attributes.iter().any(|a| match test_name {
            "is_valid_email" => a.semantic_type.as_deref() == Some("email"),
            "max_length" => {
                parse_constraint_value(&a.constraints, "max_length").is_some()
                    || a.semantic_type.as_deref() == Some("postal_code")
            }
            "not_negative" => {
                a.semantic_type.as_deref() == Some("currency_amount")
                    && parse_constraint_value(&a.constraints, "minimum")
                        .is_some_and(|v| v >= 0)
            }
            _ => false,
        })
    })
}

fn emit_generic_tests(entities: &[ContractEntity], version: &str) -> Vec<ArtifactDescriptor> {
    let mut artifacts = Vec::new();

    if needs_generic_test(entities, "is_valid_email") {
        artifacts.push(ArtifactDescriptor {
            path: "dbt/tests/generic/is_valid_email.sql".into(),
            kind: ArtifactKind::DbtTest,
            artifact_id: "art_dbt_test_is_valid_email".into(),
            generator: GENERATOR_NAME.into(),
            generator_version: version.to_owned(),
            content: format!(
                "{comment}\n\n{{% test is_valid_email(model, column_name) %}}\n\nselect\n    {{{{ column_name }}}} as invalid_email\nfrom {{{{ model }}}}\nwhere {{{{ column_name }}}} is not null\n  and {{{{ column_name }}}} not similar to '[^\\s@]+@[^\\s@]+\\.[^\\s@]+'\n\n{{% endtest %}}\n",
                comment = ownership_comment("art_dbt_test_is_valid_email", version),
            ),
            metadata_object_ids: vec![],
        });
    }

    if needs_generic_test(entities, "max_length") {
        artifacts.push(ArtifactDescriptor {
            path: "dbt/tests/generic/max_length.sql".into(),
            kind: ArtifactKind::DbtTest,
            artifact_id: "art_dbt_test_max_length".into(),
            generator: GENERATOR_NAME.into(),
            generator_version: version.to_owned(),
            content: format!(
                "{comment}\n\n{{% test max_length(model, column_name, max_value) %}}\n\nselect\n    {{{{ column_name }}}} as overlength_value\nfrom {{{{ model }}}}\nwhere length(cast({{{{ column_name }}}} as varchar)) > {{{{ max_value }}}}\n\n{{% endtest %}}\n",
                comment = ownership_comment("art_dbt_test_max_length", version),
            ),
            metadata_object_ids: vec![],
        });
    }

    if needs_generic_test(entities, "not_negative") {
        artifacts.push(ArtifactDescriptor {
            path: "dbt/tests/generic/not_negative.sql".into(),
            kind: ArtifactKind::DbtTest,
            artifact_id: "art_dbt_test_not_negative".into(),
            generator: GENERATOR_NAME.into(),
            generator_version: version.to_owned(),
            content: format!(
                "{comment}\n\n{{% test not_negative(model, column_name) %}}\n\nselect\n    {{{{ column_name }}}} as negative_value\nfrom {{{{ model }}}}\nwhere {{{{ column_name }}}} < 0\n\n{{% endtest %}}\n",
                comment = ownership_comment("art_dbt_test_not_negative", version),
            ),
            metadata_object_ids: vec![],
        });
    }

    artifacts
}

fn escape_yaml(s: &str) -> String {
    s.replace('\\', "\\\\").replace('"', "\\\"")
}

#[cfg(test)]
mod tests {
    use super::*;
    use know_now_contract::contract::{
        ContractAttribute, ContractEntity, ContractProject, ContractRelationship,
        ContractSourceColumn, ContractSourceSystem, ContractSourceTable, ContractTrace,
        GeneratorContract,
    };

    fn customer_entity() -> ContractEntity {
        ContractEntity {
            id: "ent_customer".into(),
            name: "customer".into(),
            display_name: None,
            domain: None,
            module: None,
            owner: None,
            steward: None,
            classification: None,
            retention_policy: None,
            description: Some("Core customer entity.".into()),
            entity_type: None,
            tags: vec![],
            business_key: vec!["id".into()],
            attributes: vec![
                ContractAttribute {
                    id: "attr_id".into(),
                    name: "id".into(),
                    logical_type: Some("integer".into()),
                    semantic_type: None,
                    sensitivity: None,
                    pii: None,
                    required: Some(true),
                    is_unique: Some(true),
                    constraints: vec![],
                    description: Some("Primary key.".into()),
                    attr_type: None,
                },
                ContractAttribute {
                    id: "attr_email".into(),
                    name: "email".into(),
                    logical_type: Some("string".into()),
                    semantic_type: Some("email".into()),
                    sensitivity: None,
                    pii: Some(true),
                    required: Some(true),
                    is_unique: None,
                    constraints: vec![],
                    description: Some("Contact email.".into()),
                    attr_type: None,
                },
            ],
        }
    }

    fn order_entity() -> ContractEntity {
        ContractEntity {
            id: "ent_order".into(),
            name: "order".into(),
            display_name: None,
            domain: None,
            module: None,
            owner: None,
            steward: None,
            classification: None,
            retention_policy: None,
            description: None,
            entity_type: None,
            tags: vec![],
            business_key: vec!["id".into()],
            attributes: vec![
                ContractAttribute {
                    id: "attr_order_id".into(),
                    name: "id".into(),
                    logical_type: Some("integer".into()),
                    semantic_type: None,
                    sensitivity: None,
                    pii: None,
                    required: Some(true),
                    is_unique: Some(true),
                    constraints: vec![],
                    description: None,
                    attr_type: None,
                },
                ContractAttribute {
                    id: "attr_order_customer_id".into(),
                    name: "customer_id".into(),
                    logical_type: Some("integer".into()),
                    semantic_type: None,
                    sensitivity: None,
                    pii: None,
                    required: Some(true),
                    is_unique: None,
                    constraints: vec![],
                    description: None,
                    attr_type: None,
                },
                ContractAttribute {
                    id: "attr_order_total".into(),
                    name: "total".into(),
                    logical_type: Some("decimal".into()),
                    semantic_type: None,
                    sensitivity: None,
                    pii: None,
                    required: Some(true),
                    is_unique: None,
                    constraints: vec![],
                    description: None,
                    attr_type: None,
                },
            ],
        }
    }

    fn crm_source() -> ContractSourceSystem {
        ContractSourceSystem {
            name: "crm_db".into(),
            kind: Some("database".into()),
            description: Some("CRM database.".into()),
            tables: vec![ContractSourceTable {
                name: "customers".into(),
                entity: Some("customer".into()),
                schema: Some("public".into()),
                columns: vec![
                    ContractSourceColumn {
                        source: "cust_id".into(),
                        target: "id".into(),
                        transform: None,
                    },
                    ContractSourceColumn {
                        source: "cust_email".into(),
                        target: "email".into(),
                        transform: Some("LOWER(cust_email)".into()),
                    },
                ],
            }],
        }
    }

    fn minimal_contract() -> GeneratorContract {
        GeneratorContract {
            contract_version: "1.0".into(),
            project: Some(ContractProject {
                name: "demo".into(),
                description: None,
                owner: None,
                tags: vec![],
            }),
            target_database: None,
            entities: vec![customer_entity()],
            relationships: vec![],
            source_systems: vec![crm_source()],
            quality_rules: vec![],
            governance: None,
            open_questions: vec![],
            assumptions: vec![],
            trace: ContractTrace::default(),
        }
    }

    fn multi_entity_contract() -> GeneratorContract {
        GeneratorContract {
            contract_version: "1.0".into(),
            project: Some(ContractProject {
                name: "demo".into(),
                description: None,
                owner: None,
                tags: vec![],
            }),
            target_database: None,
            entities: vec![customer_entity(), order_entity()],
            relationships: vec![ContractRelationship {
                id: "rel_order_customer".into(),
                from_entity: "order".into(),
                to_entity: "customer".into(),
                cardinality: Some("many_to_one".into()),
                from_key: Some("customer_id".into()),
                to_key: Some("id".into()),
                description: None,
            }],
            source_systems: vec![crm_source()],
            quality_rules: vec![],
            governance: None,
            open_questions: vec![],
            assumptions: vec![],
            trace: ContractTrace::default(),
        }
    }

    #[test]
    fn empty_contract_produces_no_artifacts() {
        let gen = DbtGenerator::new();
        let contract = GeneratorContract {
            contract_version: "1.0".into(),
            project: None,
            target_database: None,
            entities: vec![],
            relationships: vec![],
            source_systems: vec![],
            quality_rules: vec![],
            governance: None,
            open_questions: vec![],
            assumptions: vec![],
            trace: ContractTrace::default(),
        };
        assert!(gen.generate(&contract).unwrap().is_empty());
    }

    #[test]
    fn produces_dbt_project_yml() {
        let gen = DbtGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let project = artifacts
            .iter()
            .find(|a| a.path == "dbt/dbt_project.yml")
            .unwrap();
        assert!(project.content.contains("name: 'demo'"));
        assert!(project.content.contains("config-version: 2"));
        assert!(project.content.contains("custom/dbt/models"));
        assert!(project.content.contains("custom/dbt/macros"));
    }

    #[test]
    fn produces_sources_yml() {
        let gen = DbtGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let sources = artifacts
            .iter()
            .find(|a| a.path == "dbt/models/sources.yml")
            .unwrap();
        assert!(sources.content.contains("sources:"));
        assert!(sources.content.contains("name: crm_db"));
        assert!(sources.content.contains("name: customers"));
        assert!(sources.content.contains("schema: public"));
    }

    #[test]
    fn produces_staging_model() {
        let gen = DbtGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let stg = artifacts
            .iter()
            .find(|a| a.path.contains("stg_crm_db_customers"))
            .unwrap();
        assert!(stg.content.contains("source('crm_db', 'customers')"));
        assert!(stg.content.contains("cust_id"));
        assert!(stg.content.contains("LOWER(cust_email) as email"));
    }

    #[test]
    fn produces_staging_schema() {
        let gen = DbtGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let schema = artifacts
            .iter()
            .find(|a| a.path == "dbt/models/staging/schema.yml")
            .unwrap();
        assert!(schema.content.contains("name: stg_crm_db_customers"));
    }

    #[test]
    fn produces_mart_model() {
        let gen = DbtGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let mart = artifacts
            .iter()
            .find(|a| a.path == "dbt/models/marts/customer.sql")
            .unwrap();
        assert!(mart.content.contains("ref('customer')"));
        assert!(mart.content.contains("base.id"));
        assert!(mart.content.contains("base.email"));
    }

    #[test]
    fn mart_model_includes_joins() {
        let gen = DbtGenerator::new();
        let artifacts = gen.generate(&multi_entity_contract()).unwrap();
        let order_mart = artifacts
            .iter()
            .find(|a| a.path == "dbt/models/marts/order.sql")
            .unwrap();
        assert!(order_mart.content.contains("left join"));
        assert!(order_mart.content.contains("ref('customer')"));
        assert!(order_mart
            .content
            .contains("base.customer_id = customer.id"));
    }

    #[test]
    fn produces_marts_schema() {
        let gen = DbtGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let schema = artifacts
            .iter()
            .find(|a| a.path == "dbt/models/marts/schema.yml")
            .unwrap();
        assert!(schema.content.contains("name: customer"));
        assert!(schema.content.contains("description: \"Primary key.\""));
        assert!(schema.content.contains("not_null"));
        assert!(schema.content.contains("unique"));
    }

    #[test]
    fn deterministic_output() {
        let gen = DbtGenerator::new();
        let contract = multi_entity_contract();
        let a = gen.generate(&contract).unwrap();
        let b = gen.generate(&contract).unwrap();
        for (x, y) in a.iter().zip(b.iter()) {
            assert_eq!(x.content, y.content, "artifact {} differs", x.path);
        }
    }

    #[test]
    fn no_crlf_in_output() {
        let gen = DbtGenerator::new();
        let artifacts = gen.generate(&multi_entity_contract()).unwrap();
        for artifact in &artifacts {
            assert!(
                !artifact.content.contains('\r'),
                "NFR-PO3: LF only in {}",
                artifact.path
            );
        }
    }

    #[test]
    fn artifacts_sorted_by_path() {
        let gen = DbtGenerator::new();
        let artifacts = gen.generate(&multi_entity_contract()).unwrap();
        let paths: Vec<&str> = artifacts.iter().map(|a| a.path.as_str()).collect();
        let mut sorted = paths.clone();
        sorted.sort();
        assert_eq!(paths, sorted);
    }

    #[test]
    fn no_sources_skips_staging() {
        let gen = DbtGenerator::new();
        let contract = GeneratorContract {
            contract_version: "1.0".into(),
            project: Some(ContractProject {
                name: "demo".into(),
                description: None,
                owner: None,
                tags: vec![],
            }),
            target_database: None,
            entities: vec![customer_entity()],
            relationships: vec![],
            source_systems: vec![],
            quality_rules: vec![],
            governance: None,
            open_questions: vec![],
            assumptions: vec![],
            trace: ContractTrace::default(),
        };
        let artifacts = gen.generate(&contract).unwrap();
        assert!(!artifacts.iter().any(|a| a.path.contains("staging")));
        assert!(!artifacts.iter().any(|a| a.path.contains("sources.yml")));
        assert!(artifacts.iter().any(|a| a.path.contains("marts/customer")));
    }

    #[test]
    fn ownership_comments_present() {
        let gen = DbtGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        for artifact in &artifacts {
            let comment_prefix = if artifact.path.ends_with(".yml") {
                "# Generated by know-now."
            } else {
                "-- Generated by know-now."
            };
            assert!(
                artifact.content.starts_with(comment_prefix),
                "missing ownership comment in {}",
                artifact.path
            );
        }
    }

    #[test]
    fn project_name_sanitized() {
        let gen = DbtGenerator::new();
        let mut contract = minimal_contract();
        contract.project = Some(ContractProject {
            name: "my-project".into(),
            description: None,
            owner: None,
            tags: vec![],
        });
        let artifacts = gen.generate(&contract).unwrap();
        let project = artifacts
            .iter()
            .find(|a| a.path.ends_with("dbt_project.yml"))
            .unwrap();
        assert!(project.content.contains("name: 'my_project'"));
    }

    #[test]
    fn generator_is_send_sync() {
        fn assert_send_sync<T: Send + Sync>() {}
        assert_send_sync::<DbtGenerator>();
    }

    #[test]
    fn artifact_kinds_correct() {
        let gen = DbtGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        for a in &artifacts {
            if a.path.contains("tests/generic/") {
                assert_eq!(a.kind, ArtifactKind::DbtTest, "wrong kind for {}", a.path);
            } else if a.path.ends_with(".sql") || a.path.ends_with("dbt_project.yml") {
                assert_eq!(a.kind, ArtifactKind::DbtModel, "wrong kind for {}", a.path);
            } else if a.path.ends_with("schema.yml") || a.path.ends_with("sources.yml") {
                assert_eq!(a.kind, ArtifactKind::DbtSchema, "wrong kind for {}", a.path);
            }
        }
    }

    #[test]
    fn email_generates_is_valid_email_test() {
        let gen = DbtGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let schema = artifacts
            .iter()
            .find(|a| a.path == "dbt/models/marts/schema.yml")
            .unwrap();
        assert!(
            schema.content.contains("is_valid_email"),
            "email semantic type should generate is_valid_email test"
        );
    }

    #[test]
    fn email_generates_generic_test_sql() {
        let gen = DbtGenerator::new();
        let artifacts = gen.generate(&minimal_contract()).unwrap();
        let test = artifacts
            .iter()
            .find(|a| a.path == "dbt/tests/generic/is_valid_email.sql");
        assert!(test.is_some(), "should generate is_valid_email.sql generic test");
        let content = &test.unwrap().content;
        assert!(content.contains("{% test is_valid_email(model, column_name) %}"));
        assert!(content.contains("{% endtest %}"));
    }

    #[test]
    fn relationship_generates_relationships_test() {
        let gen = DbtGenerator::new();
        let artifacts = gen.generate(&multi_entity_contract()).unwrap();
        let schema = artifacts
            .iter()
            .find(|a| a.path == "dbt/models/marts/schema.yml")
            .unwrap();
        assert!(
            schema.content.contains("relationships:"),
            "FK should generate relationships test"
        );
        assert!(schema.content.contains("to: ref('customer')"));
        assert!(schema.content.contains("field: id"));
    }

    fn entity_with_country_code() -> ContractEntity {
        ContractEntity {
            id: "ent_address".into(),
            name: "address".into(),
            display_name: None,
            domain: None,
            module: None,
            owner: None,
            steward: None,
            classification: None,
            retention_policy: None,
            description: None,
            entity_type: None,
            tags: vec![],
            business_key: vec!["id".into()],
            attributes: vec![
                ContractAttribute {
                    id: "attr_addr_id".into(),
                    name: "id".into(),
                    logical_type: Some("integer".into()),
                    semantic_type: None,
                    sensitivity: None,
                    pii: None,
                    required: Some(true),
                    is_unique: Some(true),
                    constraints: vec![],
                    description: None,
                    attr_type: None,
                },
                ContractAttribute {
                    id: "attr_country".into(),
                    name: "country".into(),
                    logical_type: Some("string".into()),
                    semantic_type: Some("country_code".into()),
                    sensitivity: None,
                    pii: None,
                    required: Some(true),
                    is_unique: None,
                    constraints: vec![],
                    description: None,
                    attr_type: None,
                },
            ],
        }
    }

    #[test]
    fn country_code_generates_accepted_values() {
        let gen = DbtGenerator::new();
        let mut contract = minimal_contract();
        contract.entities = vec![entity_with_country_code()];
        let artifacts = gen.generate(&contract).unwrap();
        let schema = artifacts
            .iter()
            .find(|a| a.path == "dbt/models/marts/schema.yml")
            .unwrap();
        assert!(schema.content.contains("accepted_values:"));
        assert!(schema.content.contains("'US'"));
        assert!(schema.content.contains("'NL'"));
    }

    fn entity_with_max_length() -> ContractEntity {
        ContractEntity {
            id: "ent_product".into(),
            name: "product".into(),
            display_name: None,
            domain: None,
            module: None,
            owner: None,
            steward: None,
            classification: None,
            retention_policy: None,
            description: None,
            entity_type: None,
            tags: vec![],
            business_key: vec!["id".into()],
            attributes: vec![
                ContractAttribute {
                    id: "attr_prod_id".into(),
                    name: "id".into(),
                    logical_type: Some("integer".into()),
                    semantic_type: None,
                    sensitivity: None,
                    pii: None,
                    required: Some(true),
                    is_unique: Some(true),
                    constraints: vec![],
                    description: None,
                    attr_type: None,
                },
                ContractAttribute {
                    id: "attr_prod_name".into(),
                    name: "product_name".into(),
                    logical_type: Some("string".into()),
                    semantic_type: None,
                    sensitivity: None,
                    pii: None,
                    required: Some(true),
                    is_unique: None,
                    constraints: vec!["max_length:255".into()],
                    description: None,
                    attr_type: None,
                },
            ],
        }
    }

    #[test]
    fn max_length_constraint_generates_test() {
        let gen = DbtGenerator::new();
        let mut contract = minimal_contract();
        contract.entities = vec![entity_with_max_length()];
        let artifacts = gen.generate(&contract).unwrap();
        let schema = artifacts
            .iter()
            .find(|a| a.path == "dbt/models/marts/schema.yml")
            .unwrap();
        assert!(schema.content.contains("max_length:"));
        assert!(schema.content.contains("max_value: 255"));
    }

    #[test]
    fn max_length_generates_generic_test_sql() {
        let gen = DbtGenerator::new();
        let mut contract = minimal_contract();
        contract.entities = vec![entity_with_max_length()];
        let artifacts = gen.generate(&contract).unwrap();
        let test = artifacts
            .iter()
            .find(|a| a.path == "dbt/tests/generic/max_length.sql");
        assert!(test.is_some(), "should generate max_length.sql generic test");
        let content = &test.unwrap().content;
        assert!(content.contains("{% test max_length(model, column_name, max_value) %}"));
    }

    #[test]
    fn no_generic_tests_when_not_needed() {
        let gen = DbtGenerator::new();
        let mut contract = minimal_contract();
        contract.entities = vec![order_entity()];
        let artifacts = gen.generate(&contract).unwrap();
        assert!(
            !artifacts.iter().any(|a| a.path.contains("tests/generic/")),
            "should not generate generic tests when no entity needs them"
        );
    }

    #[test]
    fn parse_constraint_extracts_value() {
        let constraints = vec!["max_length:100".into(), "minimum:0".into()];
        assert_eq!(parse_constraint_value(&constraints, "max_length"), Some(100));
        assert_eq!(parse_constraint_value(&constraints, "minimum"), Some(0));
        assert_eq!(parse_constraint_value(&constraints, "unknown"), None);
    }
}
