use std::collections::BTreeMap;
use std::path::Path;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct OwnershipHeader {
    pub artifact_id: String,
    pub generator: String,
    pub input_hash: String,
}

const MANIFEST_PATH: &str = "generated/manifest.json";

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CommentStyle {
    Sql,
    Hash,
    HtmlBlock,
}

#[must_use]
pub fn comment_style_for_path(path: &Path) -> Option<CommentStyle> {
    let ext = path.extension()?.to_str()?;
    match ext {
        "sql" => Some(CommentStyle::Sql),
        "md" | "markdown" => Some(CommentStyle::HtmlBlock),
        "yml" | "yaml" => Some(CommentStyle::Hash),
        _ => None,
    }
}

#[must_use]
pub fn format_header(header: &OwnershipHeader, style: CommentStyle) -> String {
    let lines = [
        "Generated by know-now.".to_owned(),
        format!("Artifact ID: {}", header.artifact_id),
        format!("Generator: {}", header.generator),
        format!("Input hash: {}", header.input_hash),
        format!("Manifest path: {MANIFEST_PATH}"),
        "Do not edit directly unless you intend to fork this artifact.".to_owned(),
    ];

    match style {
        CommentStyle::Sql => {
            let mut out = String::new();
            for line in &lines {
                out.push_str("-- ");
                out.push_str(line);
                out.push('\n');
            }
            out.push('\n');
            out
        }
        CommentStyle::Hash => {
            let mut out = String::new();
            for line in &lines {
                out.push_str("# ");
                out.push_str(line);
                out.push('\n');
            }
            out.push('\n');
            out
        }
        CommentStyle::HtmlBlock => {
            let mut out = String::from("<!--\n");
            for line in &lines {
                out.push_str(line);
                out.push('\n');
            }
            out.push_str("-->\n\n");
            out
        }
    }
}

#[must_use]
pub fn parse_header(content: &str) -> Option<OwnershipHeader> {
    let fields = extract_header_fields(content)?;
    Some(OwnershipHeader {
        artifact_id: fields.get("Artifact ID")?.clone(),
        generator: fields.get("Generator")?.clone(),
        input_hash: fields.get("Input hash")?.clone(),
    })
}

fn extract_header_fields(content: &str) -> Option<BTreeMap<String, String>> {
    let mut fields = BTreeMap::new();
    let mut found_marker = false;

    for line in content.lines().take(20) {
        let stripped = line
            .trim_start_matches("-- ")
            .trim_start_matches("# ")
            .trim_start_matches("<!--")
            .trim_start_matches("-->")
            .trim();

        if stripped == "Generated by know-now." {
            found_marker = true;
            continue;
        }
        if !found_marker {
            continue;
        }
        if stripped.is_empty() || stripped.starts_with("Do not edit") {
            continue;
        }
        if let Some((key, value)) = stripped.split_once(": ") {
            fields.insert(key.to_owned(), value.to_owned());
        }
    }

    if found_marker && fields.len() >= 3 {
        Some(fields)
    } else {
        None
    }
}

#[must_use]
pub fn prepend_header(content: &[u8], header: &OwnershipHeader, path: &Path) -> Vec<u8> {
    let Some(style) = comment_style_for_path(path) else {
        return content.to_vec();
    };
    let header_text = format_header(header, style);
    let mut result = header_text.into_bytes();
    result.extend_from_slice(content);
    result
}

#[cfg(test)]
mod tests {
    use super::*;

    fn sample_header() -> OwnershipHeader {
        OwnershipHeader {
            artifact_id: "art_postgres_schema".into(),
            generator: "know_now_gen_postgres".into(),
            input_hash: "sha256:abc123def456".into(),
        }
    }

    #[test]
    fn sql_header_format() {
        let header = format_header(&sample_header(), CommentStyle::Sql);
        assert!(header.starts_with("-- Generated by know-now.\n"));
        assert!(header.contains("-- Artifact ID: art_postgres_schema\n"));
        assert!(header.contains("-- Generator: know_now_gen_postgres\n"));
        assert!(header.contains("-- Input hash: sha256:abc123def456\n"));
        assert!(header.contains("-- Manifest path: generated/manifest.json\n"));
        assert!(header.ends_with("\n\n"));
    }

    #[test]
    fn markdown_header_format() {
        let header = format_header(&sample_header(), CommentStyle::HtmlBlock);
        assert!(header.starts_with("<!--\n"));
        assert!(header.contains("Generated by know-now.\n"));
        assert!(header.contains("Artifact ID: art_postgres_schema\n"));
        assert!(header.contains("-->\n\n"));
    }

    #[test]
    fn yaml_header_format() {
        let header = format_header(&sample_header(), CommentStyle::Hash);
        assert!(header.starts_with("# Generated by know-now.\n"));
        assert!(header.contains("# Artifact ID: art_postgres_schema\n"));
    }

    #[test]
    fn roundtrip_sql() {
        let original = sample_header();
        let formatted = format_header(&original, CommentStyle::Sql);
        let parsed = parse_header(&formatted).expect("should parse");
        assert_eq!(original, parsed);
    }

    #[test]
    fn roundtrip_markdown() {
        let original = sample_header();
        let formatted = format_header(&original, CommentStyle::HtmlBlock);
        let parsed = parse_header(&formatted).expect("should parse");
        assert_eq!(original, parsed);
    }

    #[test]
    fn roundtrip_yaml() {
        let original = sample_header();
        let formatted = format_header(&original, CommentStyle::Hash);
        let parsed = parse_header(&formatted).expect("should parse");
        assert_eq!(original, parsed);
    }

    #[test]
    fn parse_returns_none_for_no_header() {
        assert!(parse_header("SELECT 1;").is_none());
    }

    #[test]
    fn comment_style_detection() {
        assert_eq!(
            comment_style_for_path(Path::new("schema.sql")),
            Some(CommentStyle::Sql)
        );
        assert_eq!(
            comment_style_for_path(Path::new("docs/README.md")),
            Some(CommentStyle::HtmlBlock)
        );
        assert_eq!(
            comment_style_for_path(Path::new("config.yml")),
            Some(CommentStyle::Hash)
        );
        assert_eq!(
            comment_style_for_path(Path::new("config.yaml")),
            Some(CommentStyle::Hash)
        );
        assert!(comment_style_for_path(Path::new("data.json")).is_none());
        assert!(comment_style_for_path(Path::new("binary.bin")).is_none());
    }

    #[test]
    fn prepend_header_adds_to_sql() {
        let content = b"CREATE TABLE test;";
        let header = sample_header();
        let result = prepend_header(content, &header, Path::new("schema.sql"));
        let text = String::from_utf8(result).unwrap();
        assert!(text.starts_with("-- Generated by know-now."));
        assert!(text.ends_with("CREATE TABLE test;"));
    }

    #[test]
    fn prepend_header_skips_unsupported_format() {
        let content = b"{\"key\": \"value\"}";
        let header = sample_header();
        let result = prepend_header(content, &header, Path::new("data.json"));
        assert_eq!(result, content);
    }

    #[test]
    fn header_does_not_embed_file_content_hash() {
        let header = format_header(&sample_header(), CommentStyle::Sql);
        assert!(!header.contains("Content hash"));
        assert!(!header.contains("File hash"));
    }
}
